import 'package:cleanup_app/l10n/app_localizations.dart';
import 'package:cleanup_app/l10n/locale_controller.dart';
import 'package:flutter_test/flutter_test.dart';

// Resolve every shipped message, including errors outside the happy path.
// Nested ICU expressions are evaluated at boundary counts for every locale.
void main() {
  for (final option in LocaleController.languageOptions) {
    test(
      '${option.nativeName}: complete catalog resolves at boundary counts',
      () {
        final text = lookupAppLocalizations(option.locale);
        for (final count in [0, 1, 2, 100]) {
          final samples = _catalog(text, count);
          expect(samples.length, 363);
          for (final entry in samples.entries) {
            expect(entry.value.trim(), isNotEmpty, reason: entry.key);
            expect(
              entry.value,
              isNot(contains(RegExp(r'[{}]'))),
              reason: '${entry.key} at $count',
            );
            expect(entry.value, isNot(contains('\uFFFD')), reason: entry.key);
            var isolateDepth = 0;
            for (final code in entry.value.runes) {
              if ([0x2066, 0x2067, 0x2068].contains(code)) isolateDepth++;
              if (code == 0x2069) isolateDepth--;
              expect(isolateDepth, greaterThanOrEqualTo(0), reason: entry.key);
            }
            expect(isolateDepth, 0, reason: entry.key);
          }
        }
      },
    );
  }
}

Map<String, String> _catalog(AppLocalizations text, int count) => {
  'onboardingSmartTitle': text.onboardingSmartTitle,
  'onboardingSmartSubtitle': text.onboardingSmartSubtitle,
  'onboardingPhotosTitle': text.onboardingPhotosTitle,
  'onboardingPhotosSubtitle': text.onboardingPhotosSubtitle,
  'onboardingSwipeTitle': text.onboardingSwipeTitle,
  'onboardingSwipeSubtitle': text.onboardingSwipeSubtitle,
  'onboardingChoiceTitle': text.onboardingChoiceTitle,
  'onboardingChoiceSubtitle': text.onboardingChoiceSubtitle,
  'onboardingSkip': text.onboardingSkip,
  'onboardingPreparing': text.onboardingPreparing,
  'onboardingContinue': text.onboardingContinue,
  'onboardingGetStarted': text.onboardingGetStarted,
  'paywallTitle': text.paywallTitle,
  'paywallClose': text.paywallClose,
  'paywallDescription': text.paywallDescription,
  'paywallReloadPlans': text.paywallReloadPlans,
  'paywallNotConfigured': text.paywallNotConfigured,
  'paywallContinue': text.paywallContinue,
  'paywallStoreNotice': text.paywallStoreNotice,
  'paywallRestorePurchases': text.paywallRestorePurchases,
  'paywallPrivacyPolicy': text.paywallPrivacyPolicy,
  'paywallTerms': text.paywallTerms,
  'paywallPurchaseIncomplete': text.paywallPurchaseIncomplete,
  'paywallRestored': text.paywallRestored,
  'paywallRestoreNotFound': text.paywallRestoreNotFound,
  'paywallWeeklyPlan': text.paywallWeeklyPlan,
  'paywallYearlyPlan': text.paywallYearlyPlan,
  'paywallYearlySubtitle': text.paywallYearlySubtitle,
  'paywallWeeklySubtitle': text.paywallWeeklySubtitle,
  'paywallPhotoFeature': text.paywallPhotoFeature,
  'paywallVideoFeature': text.paywallVideoFeature,
  'paywallSwipeFeature': text.paywallSwipeFeature,
  'paywallPlansUnavailable': text.paywallPlansUnavailable,
  'paywallBestValue': text.paywallBestValue,
  'videoTitle': text.videoTitle,
  'videoDescription': text.videoDescription,
  'videoProRequired': text.videoProRequired,
  'videoSaving': text.videoSaving,
  'videoCancelCompression': text.videoCancelCompression,
  'videoLoadingPreview': text.videoLoadingPreview,
  'videoCreatePreview': text.videoCreatePreview,
  'videoStorageNotice': text.videoStorageNotice,
  'videoViewOriginal': text.videoViewOriginal,
  'videoViewCopy': text.videoViewCopy,
  'videoSaved': text.videoSaved,
  'videoConfirmSave': text.videoConfirmSave,
  'videoPreviewUnavailable': text.videoPreviewUnavailable,
  'videoPlaybackUnavailable': text.videoPlaybackUnavailable,
  'videoOperationIncomplete': text.videoOperationIncomplete,
  'videoPauseOriginal': text.videoPauseOriginal,
  'videoPlayOriginal': text.videoPlayOriginal,
  'videoPauseCopy': text.videoPauseCopy,
  'videoPlayCopy': text.videoPlayCopy,
  'onboardingStep': text.onboardingStep(count, count),
  'paywallBuild': text.paywallBuild('43'),
  'videoCompressionProgress': text.videoCompressionProgress(count),
  'videoOriginalSize': text.videoOriginalSize('12.5 GB'),
  'videoCopySize': text.videoCopySize('12.5 GB'),
  'videoSizeDifference': text.videoSizeDifference('12.5 GB'),
  'videoSizeGb': text.videoSizeGb('12.5 GB'),
  'videoSizeMb': text.videoSizeMb('12.5 GB'),
  'homeStorageUnavailable': text.homeStorageUnavailable,
  'homeViewIndexedPhotos': text.homeViewIndexedPhotos,
  'homeViewIndexedScreenshots': text.homeViewIndexedScreenshots,
  'homeCleanupTools': text.homeCleanupTools,
  'homeQuickActions': text.homeQuickActions,
  'homeAppName': text.homeAppName,
  'homeSubtitle': text.homeSubtitle,
  'homeProBadge': text.homeProBadge,
  'homeStorageUsed': text.homeStorageUsed,
  'homeUsedLegend': text.homeUsedLegend,
  'homeAvailableLegend': text.homeAvailableLegend,
  'homeStartScanHint': text.homeStartScanHint,
  'homeScanning': text.homeScanning,
  'homeDeleting': text.homeDeleting,
  'homeResumeScan': text.homeResumeScan,
  'homeScanAll': text.homeScanAll,
  'homePreviewOrganize': text.homePreviewOrganize,
  'homeVerifyOriginals': text.homeVerifyOriginals,
  'homeRetryPending': text.homeRetryPending,
  'homeExactDuplicates': text.homeExactDuplicates,
  'homeSimilarPhotos': text.homeSimilarPhotos,
  'homeNotScanned': text.homeNotScanned,
  'homePendingAnalysis': text.homePendingAnalysis,
  'homeNoneAnalyzed': text.homeNoneAnalyzed,
  'homeScreenshots': text.homeScreenshots,
  'homeLargeFiles': text.homeLargeFiles,
  'homeNoneFound': text.homeNoneFound,
  'homePendingVerification': text.homePendingVerification,
  'homeNoneVerified': text.homeNoneVerified,
  'homeNeedsReview': text.homeNeedsReview,
  'homeCanReview': text.homeCanReview,
  'homeScanStatus': text.homeScanStatus,
  'homeDoneStatus': text.homeDoneStatus,
  'homePreviewPhotos': text.homePreviewPhotos,
  'homeChooseKeep': text.homeChooseKeep,
  'navHome': text.navHome,
  'navClean': text.navClean,
  'navSettings': text.navSettings,
  'settingsTitle': text.settingsTitle,
  'settingsLoading': text.settingsLoading,
  'settingsProPlan': text.settingsProPlan,
  'settingsFreePlan': text.settingsFreePlan,
  'settingsUpgrade': text.settingsUpgrade,
  'settingsStorage': text.settingsStorage,
  'settingsStorageTotal': text.settingsStorageTotal,
  'settingsStorageUsed': text.settingsStorageUsed,
  'settingsStorageAvailable': text.settingsStorageAvailable,
  'settingsGeneral': text.settingsGeneral,
  'settingsProcessingSubscription': text.settingsProcessingSubscription,
  'settingsRestorePurchases': text.settingsRestorePurchases,
  'settingsRestoredPro': text.settingsRestoredPro,
  'settingsPrivacyPolicy': text.settingsPrivacyPolicy,
  'settingsTerms': text.settingsTerms,
  'settingsRateApp': text.settingsRateApp,
  'settingsAbout': text.settingsAbout,
  'settingsVersion': text.settingsVersion,
  'settingsLanguage': text.settingsLanguage,
  'settingsChooseLanguage': text.settingsChooseLanguage,
  'settingsSystemLanguage': text.settingsSystemLanguage,
  'homeUsedPercent': text.homeUsedPercent(count),
  'homeStorageTotal': text.homeStorageTotal('12.5 GB'),
  'homeIndexedCount': text.homeIndexedCount(count),
  'homeIndexedCountWithTotal': text.homeIndexedCountWithTotal(count, count),
  'homeAnalysisSummary': text.homeAnalysisSummary(count, count),
  'homePhotoCount': text.homePhotoCount(count),
  'homePhotoCountPartial': text.homePhotoCountPartial(count),
  'homeItemCount': text.homeItemCount(count),
  'homeVerifiedPhotosPending': text.homeVerifiedPhotosPending(count),
  'homeVerifiedItemsPending': text.homeVerifiedItemsPending(count),
  'settingsLanguageSaveError': text.settingsLanguageSaveError,
  'scanSmartTitle': text.scanSmartTitle,
  'scanCancelKeepProgress': text.scanCancelKeepProgress,
  'scanSwipeCleanup': text.scanSwipeCleanup,
  'scanSortFileSize': text.scanSortFileSize,
  'scanSortNewest': text.scanSortNewest,
  'scanStartAlbumTitle': text.scanStartAlbumTitle,
  'scanIncompleteTitle': text.scanIncompleteTitle,
  'scanStartAlbumDescription': text.scanStartAlbumDescription,
  'scanContinue': text.scanContinue,
  'scanStart': text.scanStart,
  'scanPreviewWhileRunning': text.scanPreviewWhileRunning,
  'scanExactDescription': text.scanExactDescription,
  'scanSimilarDescription': text.scanSimilarDescription,
  'scanLargeDescription': text.scanLargeDescription,
  'scanManualDeleteDescription': text.scanManualDeleteDescription,
  'scanVerifyOriginals': text.scanVerifyOriginals,
  'scanResumePending': text.scanResumePending,
  'scanKeepReasonDefault': text.scanKeepReasonDefault,
  'scanRestoreKeepSuggestion': text.scanRestoreKeepSuggestion,
  'scanDismissKeepSuggestion': text.scanDismissKeepSuggestion,
  'scanKeepManualHint': text.scanKeepManualHint,
  'scanEmptyUnverified': text.scanEmptyUnverified,
  'scanEmptyVisualPending': text.scanEmptyVisualPending,
  'scanEmptyIndexing': text.scanEmptyIndexing,
  'scanEmptyCategory': text.scanEmptyCategory,
  'scanKeepBadge': text.scanKeepBadge,
  'scanZoomPreview': text.scanZoomPreview,
  'scanCompressVideo': text.scanCompressVideo,
  'scanContentPending': text.scanContentPending,
  'scanBackToCompare': text.scanBackToCompare,
  'scanConfirmDeleteTitle': text.scanConfirmDeleteTitle,
  'scanCancel': text.scanCancel,
  'scanNoItemsDeleted': text.scanNoItemsDeleted,
  'scanConfirmDelete': text.scanConfirmDelete,
  'scanCategoryPhotos': text.scanCategoryPhotos,
  'scanCategoryExact': text.scanCategoryExact,
  'scanCategorySimilar': text.scanCategorySimilar,
  'scanCategoryScreenshots': text.scanCategoryScreenshots,
  'scanCategoryVideos': text.scanCategoryVideos,
  'scanCategoryLarge': text.scanCategoryLarge,
  'scanExactGroupCount': text.scanExactGroupCount(count),
  'scanSimilarGroupCount': text.scanSimilarGroupCount(count),
  'scanRecommendedKeep': text.scanRecommendedKeep('preview guidance'),
  'scanSelectedCount': text.scanSelectedCount(count),
  'scanPreviewDeleteCount': text.scanPreviewDeleteCount(count),
  'scanConfirmDeleteDescription': text.scanConfirmDeleteDescription(count),
  'scanItemsDeleted': text.scanItemsDeleted(count),
  'scanIndexingTitle': text.scanIndexingTitle,
  'scanVerifyingTitle': text.scanVerifyingTitle,
  'scanAnalyzingTitle': text.scanAnalyzingTitle,
  'scanSlowOperationHint': text.scanSlowOperationHint,
  'scanProgressPreviewHint': text.scanProgressPreviewHint,
  'scanCountConfirming': text.scanCountConfirming,
  'scanIndexedCount': text.scanIndexedCount(count, '100'),
  'scanPreviewAttemptCount': text.scanPreviewAttemptCount(count, count),
  'scanOriginalAttemptCount': text.scanOriginalAttemptCount(count, count),
  'scanVisualSuccessCount': text.scanVisualSuccessCount(count),
  'scanOriginalVerifiedCount': text.scanOriginalVerifiedCount(count),
  'scanCloudPendingCount': text.scanCloudPendingCount(count),
  'scanStageRemainingCount': text.scanStageRemainingCount(count),
  'scanOperationWait': text.scanOperationWait('loading photo', count),
  'swipeKeep': text.swipeKeep,
  'swipeDelete': text.swipeDelete,
  'swipeReviewComplete': text.swipeReviewComplete,
  'swipeRecoveredSpaceHint': text.swipeRecoveredSpaceHint,
  'swipeUndoChoice': text.swipeUndoChoice,
  'swipeBack': text.swipeBack,
  'swipeConfirmDeleteTitle': text.swipeConfirmDeleteTitle,
  'swipeCancel': text.swipeCancel,
  'swipeConfirmDelete': text.swipeConfirmDelete,
  'swipeNoPhotosDeleted': text.swipeNoPhotosDeleted,
  'swipeExitTitle': text.swipeExitTitle,
  'swipeContinueReview': text.swipeContinueReview,
  'swipeLeave': text.swipeLeave,
  'swipeSkipRemainingTitle': text.swipeSkipRemainingTitle,
  'swipeDone': text.swipeDone,
  'swipeDoneCount': text.swipeDoneCount(count),
  'swipeProgressCount': text.swipeProgressCount(count, count),
  'swipeDeleteCount': text.swipeDeleteCount(count),
  'swipeKeepCount': text.swipeKeepCount(count),
  'swipeReviewSummary': text.swipeReviewSummary(count, count),
  'swipeDeletePhotos': text.swipeDeletePhotos(count),
  'swipeConfirmDeleteDescription': text.swipeConfirmDeleteDescription(count),
  'swipePartialDeleted': text.swipePartialDeleted(count),
  'swipeExitDescription': text.swipeExitDescription(count),
  'swipeSkipRemainingDescription': text.swipeSkipRemainingDescription(
    count,
    count,
  ),
  'assetDimensions': text.assetDimensions(count, count),
  'assetPreviewDetails': text.assetPreviewDetails(count, count, '12.5 GB'),
  'assetReloadPreview': text.assetReloadPreview,
  'assetSizeUnknown': text.assetSizeUnknown,
  'assetSizeGigabytes': text.assetSizeGigabytes('12.5'),
  'assetSizeMegabytes': text.assetSizeMegabytes('12.5'),
  'assetSizeKilobytes': text.assetSizeKilobytes('12.5'),
  'assetSizeBytes': text.assetSizeBytes(count),
  'appName': text.appName,
  'nativePhotoRead': text.nativePhotoRead,
  'nativePhotoAdd': text.nativePhotoAdd,
  'nativeContacts': text.nativeContacts,
  'nativeTracking': text.nativeTracking,
  'serviceSubscriptionsUnavailable': text.serviceSubscriptionsUnavailable,
  'serviceSubscriptionInitFailed': text.serviceSubscriptionInitFailed,
  'serviceNoPlans': text.serviceNoPlans,
  'servicePlansLoadFailed': text.servicePlansLoadFailed,
  'servicePurchaseUnavailable': text.servicePurchaseUnavailable,
  'servicePurchaseFailed': text.servicePurchaseFailed,
  'serviceRestoreUnavailable': text.serviceRestoreUnavailable,
  'serviceNoSubscription': text.serviceNoSubscription,
  'serviceRestoreFailed': text.serviceRestoreFailed,
  'servicePurchaseCancelled': text.servicePurchaseCancelled,
  'serviceScanPaused': text.serviceScanPaused,
  'serviceLimitedLibrary': text.serviceLimitedLibrary,
  'serviceNativeAnalysisUnavailable': text.serviceNativeAnalysisUnavailable,
  'serviceOriginalVerificationNeeded': text.serviceOriginalVerificationNeeded,
  'serviceReadingIndex': text.serviceReadingIndex,
  'servicePhotoPermission': text.servicePhotoPermission,
  'serviceOriginalRoundLimit': text.serviceOriginalRoundLimit,
  'servicePreviewRoundLimit': text.servicePreviewRoundLimit,
  'serviceReadTimeout': text.serviceReadTimeout,
  'serviceReadInterrupted': text.serviceReadInterrupted,
  'serviceVerifyingOriginals': text.serviceVerifyingOriginals,
  'serviceGroupingSimilar': text.serviceGroupingSimilar,
  'serviceQualityLowDetail': text.serviceQualityLowDetail,
  'serviceQualityDecodeFailed': text.serviceQualityDecodeFailed,
  'serviceQualityLowInformation': text.serviceQualityLowInformation,
  'serviceQualityClearEdges': text.serviceQualityClearEdges,
  'serviceQualityLessDetail': text.serviceQualityLessDetail,
  'serviceQualityDark': text.serviceQualityDark,
  'serviceQualityBright': text.serviceQualityBright,
  'serviceQualityBalanced': text.serviceQualityBalanced,
  'serviceKeepExact': text.serviceKeepExact,
  'serviceKeepHigherResolution': text.serviceKeepHigherResolution,
  'serviceVideoMissing': text.serviceVideoMissing,
  'serviceVideoCloud': text.serviceVideoCloud,
  'serviceVideoUnreadable': text.serviceVideoUnreadable,
  'serviceVideoPreviousBusy': text.serviceVideoPreviousBusy,
  'serviceVideoTemporaryUnavailable': text.serviceVideoTemporaryUnavailable,
  'serviceVideoUnsupported': text.serviceVideoUnsupported,
  'serviceVideoOutputInvalid': text.serviceVideoOutputInvalid,
  'serviceVideoSaveUnknown': text.serviceVideoSaveUnknown,
  'serviceVideoCancelled': text.serviceVideoCancelled,
  'serviceVideoOperationBusy': text.serviceVideoOperationBusy,
  'serviceVideoEmpty': text.serviceVideoEmpty,
  'serviceVideoEncodeFailed': text.serviceVideoEncodeFailed,
  'serviceVideoNoCopy': text.serviceVideoNoCopy,
  'serviceVideoNotSmaller': text.serviceVideoNotSmaller,
  'serviceVideoDurationMismatch': text.serviceVideoDurationMismatch,
  'serviceVideoValidationFailed': text.serviceVideoValidationFailed,
  'serviceVideoPreviewFirst': text.serviceVideoPreviewFirst,
  'serviceVideoSaveFailed': text.serviceVideoSaveFailed,
  'serviceVideoGenericFailed': text.serviceVideoGenericFailed,
  'serviceOperationFailed': text.serviceOperationFailed,
  'serviceIndexReadCount': text.serviceIndexReadCount(count, count),
  'servicePhotosPending': text.servicePhotosPending(count),
  'serviceReadingPreviews': text.serviceReadingPreviews(count),
  'serviceAnalyzingPreviews': text.serviceAnalyzingPreviews(count),
  'serviceQualitySummary': text.serviceQualitySummary('preview guidance'),
  'scanSwipeIntro': text.scanSwipeIntro,
  'scanSwipeStart': text.scanSwipeStart,
  'scanDetails': text.scanDetails,
  'scanVerificationNeeded': text.scanVerificationNeeded,
  'scanVerificationProgress': text.scanVerificationProgress(count, count),
  'scanVerificationExplanation': text.scanVerificationExplanation,
  'scanVerifyNow': text.scanVerifyNow,
  'scanBrowsePhotos': text.scanBrowsePhotos,
  'scanSelectAll': text.scanSelectAll,
  'scanClearSelection': text.scanClearSelection,
  'scanKeepOneSelectOthers': text.scanKeepOneSelectOthers,
  'scanSelectOthersHint': text.scanSelectOthersHint,
  'scanNotChecked': text.scanNotChecked,
  'scanPendingCheckCount': text.scanPendingCheckCount(count),
  'swipeMultiSelectTitle': text.swipeMultiSelectTitle,
  'swipeMarkSelectedForDeletion': text.swipeMarkSelectedForDeletion(count),
  'swipeGestureTitle': text.swipeGestureTitle,
  'swipeGestureDelete': text.swipeGestureDelete,
  'swipeGestureKeep': text.swipeGestureKeep,
  'swipeGestureSafety': text.swipeGestureSafety,
  'swipeGestureHelp': text.swipeGestureHelp,
  'homeSwipeDescription': text.homeSwipeDescription,
  'scanCheckExactPhotos': text.scanCheckExactPhotos,
  'scanCheckFileSizes': text.scanCheckFileSizes,
  'reviewDeleteTitle': text.reviewDeleteTitle,
  'reviewRemove': text.reviewRemove,
  'reviewUnavailable': text.reviewUnavailable,
  'reviewUnseenCount': text.reviewUnseenCount(count),
  'reviewAllVersions': text.reviewAllVersions,
  'reviewDeleteAllVersions': text.reviewDeleteAllVersions,
  'reviewConfirmCount': text.reviewConfirmCount(count),
  'swipeResumeReview': text.swipeResumeReview(count),
  'swipeResetReview': text.swipeResetReview,
  'swipeBatchSize': text.swipeBatchSize(count),
  'swipeAllMonths': text.swipeAllMonths,
  'swipeReviewBatch': text.swipeReviewBatch,
  'assetVideoLoading': text.assetVideoLoading,
  'assetVideoUnavailable': text.assetVideoUnavailable,
  'homePermissionTitle': text.homePermissionTitle,
  'homePermissionDescription': text.homePermissionDescription,
  'homeOpenSettings': text.homeOpenSettings,
  'homeManagePhotoAccess': text.homeManagePhotoAccess,
  'homeReviewReady': text.homeReviewReady,
  'homeContinueAnalysis': text.homeContinueAnalysis,
  'homeScanDetails': text.homeScanDetails,
  'scanCheckingExactTitle': text.scanCheckingExactTitle,
  'scanCheckingSizesTitle': text.scanCheckingSizesTitle,
  'scanRoundProgress': text.scanRoundProgress(count, count),
  'scanPauseReview': text.scanPauseReview,
  'scanSelectionHint': text.scanSelectionHint,
  'scanPreviewNotReady': text.scanPreviewNotReady,
  'scanUnreadableExcluded': text.scanUnreadableExcluded(count),
  'scanKeepThis': text.scanKeepThis,
  'scanPreviewMore': text.scanPreviewMore,
  'homeKnownLibrarySize': text.homeKnownLibrarySize(count, '12.5 GB'),
  'homePendingSizes': text.homePendingSizes(count),
  'scanReviewChanged': text.scanReviewChanged,
  'paywallFreePreviewNote': text.paywallFreePreviewNote,
  'paywallSubscribeWeekly': text.paywallSubscribeWeekly('USD 4.99'),
  'paywallSubscribeYearly': text.paywallSubscribeYearly('USD 4.99'),
  'paywallSubscribe': text.paywallSubscribe,
  'paywallWeeklyRenewal': text.paywallWeeklyRenewal('USD 4.99'),
  'paywallYearlyRenewal': text.paywallYearlyRenewal('USD 4.99'),
  'paywallRenewalGeneric': text.paywallRenewalGeneric,
  'paywallLoadingPlans': text.paywallLoadingPlans,
  'paywallWaitingForStore': text.paywallWaitingForStore,
  'paywallRestoring': text.paywallRestoring,
  'settingsCheckingSubscription': text.settingsCheckingSubscription,
  'settingsSubscriptionUnknown': text.settingsSubscriptionUnknown,
  'settingsManageSubscription': text.settingsManageSubscription,
  'settingsManageUnavailable': text.settingsManageUnavailable,
  'onboardingStartFree': text.onboardingStartFree,
  'swipeCheckpointSaveError': text.swipeCheckpointSaveError,
  'swipeCheckpointLimit': text.swipeCheckpointLimit(count),
  'scanSelectLoaded': text.scanSelectLoaded,
  'homePhotoScopeChanged': text.homePhotoScopeChanged,
};
