"""UI v2 strings (2026-09-29). Run `python scripts/v2_strings.py` to merge
them into lib/l10n/app_*.arb, then `flutter gen-l10n`.

Each entry: key -> {language: message}. English is the template.
String placeholders are wrapped in FSI/PDI isolates for Arabic and Hebrew.
"""
import json
from collections import OrderedDict
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
L10N = ROOT / 'lib' / 'l10n'

# Placeholder types for the English template metadata.
PLACEHOLDERS = {
    'v2StorageUsedOf': {'used': 'String', 'total': 'String'},
    'v2PhotoCount': {'count': 'int'},
    'v2VideoCount': {'count': 'int'},
    'v2ItemCount': {'count': 'int'},
    'v2DeleteCount': {'count': 'int'},
    'v2DeleteVideos': {'count': 'int'},
    'v2SelectedCount': {'count': 'int'},
    'v2FreeCleanupsLeft': {'count': 'int'},
    'v2CongratsSaved': {'minutes': 'int'},
    'v2ScanningCount': {'done': 'int', 'total': 'int'},
    'v2PermissionBody': {'appName': 'String'},
    'v2WelcomeTitle': {'appName': 'String'},
    'v2WelcomeAccess': {'appName': 'String'},
    'v2CongratsUsing': {'appName': 'String'},
    'v2DeleteSize': {'size': 'String'},
    'v2CongratsRecentlyDeleted': {'size': 'String'},
    'v2PerWeek': {'price': 'String'},
    'v2PerYear': {'price': 'String'},
    'v2FreeThen': {'days': 'int', 'price': 'String'},
    'v2FreeTrialDays': {'days': 'int'},
    'v2StartFreeTrial': {'days': 'int'},
    'v2TryDays': {'days': 'int'},
    'v2DaysFree': {'days': 'int'},
    'v2DueOn': {'date': 'String'},
    'v2SavePercent': {'percent': 'int'},
}

LANGS = ['en', 'ar', 'de', 'es', 'fr', 'he', 'id', 'it', 'ja', 'ko', 'pl',
         'pt', 'ro', 'ru', 'th', 'tr', 'vi', 'zh_Hans', 'zh_Hant']

S = {}


def s(key, **messages):
    S[key] = messages


s('navOptimize', en='Optimize', ar='تحسين', de='Optimieren', es='Optimizar',
  fr='Optimiser', he='אופטימיזציה', id='Optimalkan', it='Ottimizza',
  ja='最適化', ko='최적화', pl='Optymalizuj', pt='Otimizar', ro='Optimizare',
  ru='Оптимизация', th='ปรับให้เหมาะ', tr='Optimize Et', vi='Tối ưu',
  zh_Hans='优化', zh_Hant='最佳化')
s('navExtras', en='Extras', ar='المزيد', de='Mehr', es='Más', fr='Plus',
  he='עוד', id='Lainnya', it='Altro', ja='その他', ko='더보기', pl='Więcej',
  pt='Mais', ro='Mai mult', ru='Ещё', th='เพิ่มเติม', tr='Diğer',
  vi='Thêm', zh_Hans='更多', zh_Hant='更多')
s('v2Before', en='Before', ar='قبل', de='Vorher', es='Antes', fr='Avant',
  he='לפני', id='Sebelum', it='Prima', ja='前', ko='이전', pl='Przed',
  pt='Antes', ro='Înainte', ru='До', th='ก่อน', tr='Önce', vi='Trước',
  zh_Hans='清理前', zh_Hant='清理前')
s('v2After', en='After', ar='بعد', de='Nachher', es='Después', fr='Après',
  he='אחרי', id='Sesudah', it='Dopo', ja='後', ko='이후', pl='Po',
  pt='Depois', ro='După', ru='После', th='หลัง', tr='Sonra', vi='Sau',
  zh_Hans='清理后', zh_Hant='清理後')
s('v2Best', en='Best', ar='الأفضل', de='Beste', es='Mejor', fr='Meilleure',
  he='הטובה', id='Terbaik', it='Migliore', ja='ベスト', ko='베스트',
  pl='Najlepsze', pt='Melhor', ro='Cea mai bună', ru='Лучшее', th='ดีที่สุด',
  tr='En iyi', vi='Đẹp nhất', zh_Hans='最佳', zh_Hant='最佳')
s('v2Cancel', en='Cancel', ar='إلغاء', de='Abbrechen', es='Cancelar',
  fr='Annuler', he='ביטול', id='Batal', it='Annulla', ja='キャンセル',
  ko='취소', pl='Anuluj', pt='Cancelar', ro='Anulează', ru='Отмена',
  th='ยกเลิก', tr='Vazgeç', vi='Hủy', zh_Hans='取消', zh_Hant='取消')
s('v2Select', en='Select', ar='تحديد', de='Auswählen', es='Seleccionar',
  fr='Sélectionner', he='בחירה', id='Pilih', it='Seleziona', ja='選択',
  ko='선택', pl='Zaznacz', pt='Selecionar', ro='Selectează', ru='Выбрать',
  th='เลือก', tr='Seç', vi='Chọn', zh_Hans='选择', zh_Hant='選擇')
s('v2SelectAll', en='Select All', ar='تحديد الكل', de='Alle auswählen',
  es='Seleccionar todo', fr='Tout sélectionner', he='בחירת הכול',
  id='Pilih semua', it='Seleziona tutto', ja='すべて選択', ko='전체 선택',
  pl='Zaznacz wszystko', pt='Selecionar tudo', ro='Selectează tot',
  ru='Выбрать все', th='เลือกทั้งหมด', tr='Tümünü seç', vi='Chọn tất cả',
  zh_Hans='全选', zh_Hant='全選')
s('v2DeselectAll', en='Deselect All', ar='إلغاء تحديد الكل',
  de='Auswahl aufheben', es='Anular selección', fr='Tout désélectionner',
  he='ביטול הבחירה', id='Batalkan semua', it='Deseleziona tutto',
  ja='すべて解除', ko='전체 해제', pl='Odznacz wszystko',
  pt='Desmarcar tudo', ro='Deselectează tot', ru='Снять выбор',
  th='ยกเลิกทั้งหมด', tr='Seçimi kaldır', vi='Bỏ chọn tất cả',
  zh_Hans='取消全选', zh_Hant='取消全選')
s('v2SelectedCount', en='{count} selected', ar='تم تحديد {count}',
  de='{count} ausgewählt', es='{count} seleccionados',
  fr='{count} sélectionné(s)', he='{count} נבחרו', id='{count} dipilih',
  it='{count} selezionati', ja='{count}件選択', ko='{count}개 선택됨',
  pl='Zaznaczono: {count}', pt='{count} selecionados',
  ro='{count} selectate', ru='Выбрано: {count}', th='เลือกแล้ว {count}',
  tr='{count} seçildi', vi='Đã chọn {count}', zh_Hans='已选 {count} 项',
  zh_Hant='已選 {count} 項')

# ── Categories ──
s('v2CatSimilars', en='Similar', ar='متشابهة', de='Ähnliche', es='Similares',
  fr='Similaires', he='דומות', id='Mirip', it='Simili', ja='類似',
  ko='유사한 사진', pl='Podobne', pt='Semelhantes', ro='Similare',
  ru='Похожие', th='คล้ายกัน', tr='Benzerler', vi='Tương tự',
  zh_Hans='相似照片', zh_Hant='相似照片')
s('v2CatDuplicates', en='Duplicates', ar='المكررة', de='Duplikate',
  es='Duplicados', fr='Doublons', he='כפולות', id='Duplikat',
  it='Duplicati', ja='重複', ko='중복 사진', pl='Duplikaty',
  pt='Duplicados', ro='Duplicate', ru='Дубликаты', th='รูปซ้ำ',
  tr='Kopyalar', vi='Trùng lặp', zh_Hans='重复照片', zh_Hant='重複照片')
s('v2CatVideos', en='Videos', ar='الفيديوهات', de='Filme', es='Vídeos',
  fr='Vidéos', he='סרטונים', id='Video', it='Video', ja='ビデオ',
  ko='동영상', pl='Filmy', pt='Vídeos', ro='Clipuri', ru='Видео',
  th='วิดีโอ', tr='Videolar', vi='Video', zh_Hans='视频', zh_Hant='影片')
s('v2CatScreenshots', en='Screenshots', ar='لقطات الشاشة',
  de='Bildschirmfotos', es='Capturas', fr="Captures d'écran",
  he='צילומי מסך', id='Tangkapan layar', it='Screenshot', ja='スクリーンショット',
  ko='스크린샷', pl='Zrzuty ekranu', pt='Capturas de ecrã',
  ro='Capturi de ecran', ru='Скриншоты', th='ภาพหน้าจอ',
  tr='Ekran görüntüleri', vi='Ảnh chụp màn hình', zh_Hans='截图',
  zh_Hant='螢幕截圖')
s('v2CatBlurred', en='Blurred', ar='ضبابية', de='Unscharf', es='Borrosas',
  fr='Floues', he='מטושטשות', id='Buram', it='Sfocate', ja='ぼやけた写真',
  ko='흐린 사진', pl='Rozmyte', pt='Desfocadas', ro='Neclare',
  ru='Размытые', th='ภาพเบลอ', tr='Bulanık', vi='Bị mờ',
  zh_Hans='模糊照片', zh_Hant='模糊照片')
s('v2CatLarge', en='Large Files', ar='الملفات الكبيرة', de='Große Dateien',
  es='Archivos grandes', fr='Gros fichiers', he='קבצים גדולים',
  id='File besar', it='File grandi', ja='大きなファイル', ko='대용량 파일',
  pl='Duże pliki', pt='Ficheiros grandes', ro='Fișiere mari',
  ru='Большие файлы', th='ไฟล์ขนาดใหญ่', tr='Büyük dosyalar',
  vi='Tệp lớn', zh_Hans='大文件', zh_Hant='大型檔案')
s('v2CatOther', en='Other', ar='أخرى', de='Sonstige', es='Otras',
  fr='Autres', he='אחרות', id='Lainnya', it='Altre', ja='その他',
  ko='기타', pl='Inne', pt='Outras', ro='Altele', ru='Другие',
  th='อื่นๆ', tr='Diğerleri', vi='Khác', zh_Hans='其他照片',
  zh_Hant='其他照片')

# ── Counts ──
s('v2PhotoCount',
  en='{count, plural, one{1 Photo} other{{count} Photos}}',
  ar='{count, plural, zero{لا صور} one{صورة واحدة} two{صورتان} few{{count} صور} many{{count} صورة} other{{count} صورة}}',
  de='{count, plural, one{1 Foto} other{{count} Fotos}}',
  es='{count, plural, one{1 foto} other{{count} fotos}}',
  fr='{count, plural, one{{count} photo} other{{count} photos}}',
  he='{count, plural, one{תמונה אחת} two{שתי תמונות} other{{count} תמונות}}',
  id='{count, plural, other{{count} foto}}',
  it='{count, plural, one{1 foto} other{{count} foto}}',
  ja='{count, plural, other{{count}枚}}',
  ko='{count, plural, other{사진 {count}장}}',
  pl='{count, plural, one{{count} zdjęcie} few{{count} zdjęcia} many{{count} zdjęć} other{{count} zdjęcia}}',
  pt='{count, plural, one{1 foto} other{{count} fotos}}',
  ro='{count, plural, one{1 fotografie} few{{count} fotografii} other{{count} de fotografii}}',
  ru='{count, plural, one{{count} фото} few{{count} фото} many{{count} фото} other{{count} фото}}',
  th='{count, plural, other{{count} รูป}}',
  tr='{count, plural, other{{count} fotoğraf}}',
  vi='{count, plural, other{{count} ảnh}}',
  zh_Hans='{count, plural, other{{count} 张照片}}',
  zh_Hant='{count, plural, other{{count} 張照片}}')
s('v2VideoCount',
  en='{count, plural, one{1 Video} other{{count} Videos}}',
  ar='{count, plural, zero{لا فيديوهات} one{فيديو واحد} two{فيديوهان} few{{count} فيديوهات} many{{count} فيديو} other{{count} فيديو}}',
  de='{count, plural, one{1 Video} other{{count} Videos}}',
  es='{count, plural, one{1 vídeo} other{{count} vídeos}}',
  fr='{count, plural, one{{count} vidéo} other{{count} vidéos}}',
  he='{count, plural, one{סרטון אחד} two{שני סרטונים} other{{count} סרטונים}}',
  id='{count, plural, other{{count} video}}',
  it='{count, plural, one{1 video} other{{count} video}}',
  ja='{count, plural, other{{count}本のビデオ}}',
  ko='{count, plural, other{동영상 {count}개}}',
  pl='{count, plural, one{{count} film} few{{count} filmy} many{{count} filmów} other{{count} filmu}}',
  pt='{count, plural, one{1 vídeo} other{{count} vídeos}}',
  ro='{count, plural, one{1 clip} few{{count} clipuri} other{{count} de clipuri}}',
  ru='{count, plural, one{{count} видео} few{{count} видео} many{{count} видео} other{{count} видео}}',
  th='{count, plural, other{{count} วิดีโอ}}',
  tr='{count, plural, other{{count} video}}',
  vi='{count, plural, other{{count} video}}',
  zh_Hans='{count, plural, other{{count} 个视频}}',
  zh_Hant='{count, plural, other{{count} 部影片}}')
s('v2ItemCount',
  en='{count, plural, one{1 item} other{{count} items}}',
  ar='{count, plural, zero{لا عناصر} one{عنصر واحد} two{عنصران} few{{count} عناصر} many{{count} عنصرًا} other{{count} عنصر}}',
  de='{count, plural, one{1 Objekt} other{{count} Objekte}}',
  es='{count, plural, one{1 elemento} other{{count} elementos}}',
  fr='{count, plural, one{{count} élément} other{{count} éléments}}',
  he='{count, plural, one{פריט אחד} two{שני פריטים} other{{count} פריטים}}',
  id='{count, plural, other{{count} item}}',
  it='{count, plural, one{1 elemento} other{{count} elementi}}',
  ja='{count, plural, other{{count}件}}',
  ko='{count, plural, other{{count}개 항목}}',
  pl='{count, plural, one{{count} element} few{{count} elementy} many{{count} elementów} other{{count} elementu}}',
  pt='{count, plural, one{1 item} other{{count} itens}}',
  ro='{count, plural, one{1 element} few{{count} elemente} other{{count} de elemente}}',
  ru='{count, plural, one{{count} объект} few{{count} объекта} many{{count} объектов} other{{count} объекта}}',
  th='{count, plural, other{{count} รายการ}}',
  tr='{count, plural, other{{count} öge}}',
  vi='{count, plural, other{{count} mục}}',
  zh_Hans='{count, plural, other{{count} 项}}',
  zh_Hant='{count, plural, other{{count} 項}}')
s('v2DeleteCount',
  en='{count, plural, one{Delete 1 Item} other{Delete {count} Items}}',
  ar='{count, plural, zero{حذف} one{حذف عنصر واحد} two{حذف عنصرين} few{حذف {count} عناصر} many{حذف {count} عنصرًا} other{حذف {count} عنصر}}',
  de='{count, plural, one{1 Objekt löschen} other{{count} Objekte löschen}}',
  es='{count, plural, one{Eliminar 1 elemento} other{Eliminar {count} elementos}}',
  fr='{count, plural, one{Supprimer {count} élément} other{Supprimer {count} éléments}}',
  he='{count, plural, one{מחיקת פריט אחד} two{מחיקת שני פריטים} other{מחיקת {count} פריטים}}',
  id='{count, plural, other{Hapus {count} item}}',
  it='{count, plural, one{Elimina 1 elemento} other{Elimina {count} elementi}}',
  ja='{count, plural, other{{count}件を削除}}',
  ko='{count, plural, other{{count}개 삭제}}',
  pl='{count, plural, one{Usuń {count} element} few{Usuń {count} elementy} many{Usuń {count} elementów} other{Usuń {count} elementu}}',
  pt='{count, plural, one{Apagar 1 item} other{Apagar {count} itens}}',
  ro='{count, plural, one{Șterge 1 element} few{Șterge {count} elemente} other{Șterge {count} de elemente}}',
  ru='{count, plural, one{Удалить {count} объект} few{Удалить {count} объекта} many{Удалить {count} объектов} other{Удалить {count} объекта}}',
  th='{count, plural, other{ลบ {count} รายการ}}',
  tr='{count, plural, other{{count} ögeyi sil}}',
  vi='{count, plural, other{Xóa {count} mục}}',
  zh_Hans='{count, plural, other{删除 {count} 项}}',
  zh_Hant='{count, plural, other{刪除 {count} 項}}')
s('v2DeleteVideos',
  en='{count, plural, one{Delete 1 Video} other{Delete {count} Videos}}',
  ar='{count, plural, zero{حذف} one{حذف فيديو واحد} two{حذف فيديوهين} few{حذف {count} فيديوهات} many{حذف {count} فيديو} other{حذف {count} فيديو}}',
  de='{count, plural, one{1 Video löschen} other{{count} Videos löschen}}',
  es='{count, plural, one{Eliminar 1 vídeo} other{Eliminar {count} vídeos}}',
  fr='{count, plural, one{Supprimer {count} vidéo} other{Supprimer {count} vidéos}}',
  he='{count, plural, one{מחיקת סרטון אחד} two{מחיקת שני סרטונים} other{מחיקת {count} סרטונים}}',
  id='{count, plural, other{Hapus {count} video}}',
  it='{count, plural, one{Elimina 1 video} other{Elimina {count} video}}',
  ja='{count, plural, other{{count}本のビデオを削除}}',
  ko='{count, plural, other{동영상 {count}개 삭제}}',
  pl='{count, plural, one{Usuń {count} film} few{Usuń {count} filmy} many{Usuń {count} filmów} other{Usuń {count} filmu}}',
  pt='{count, plural, one{Apagar 1 vídeo} other{Apagar {count} vídeos}}',
  ro='{count, plural, one{Șterge 1 clip} few{Șterge {count} clipuri} other{Șterge {count} de clipuri}}',
  ru='{count, plural, one{Удалить {count} видео} few{Удалить {count} видео} many{Удалить {count} видео} other{Удалить {count} видео}}',
  th='{count, plural, other{ลบ {count} วิดีโอ}}',
  tr='{count, plural, other{{count} videoyu sil}}',
  vi='{count, plural, other{Xóa {count} video}}',
  zh_Hans='{count, plural, other{删除 {count} 个视频}}',
  zh_Hant='{count, plural, other{刪除 {count} 部影片}}')
s('v2DeleteSize', en='Delete {size}', ar='حذف {size}', de='{size} löschen',
  es='Eliminar {size}', fr='Supprimer {size}', he='מחיקת {size}',
  id='Hapus {size}', it='Elimina {size}', ja='{size}を削除',
  ko='{size} 삭제', pl='Usuń {size}', pt='Apagar {size}',
  ro='Șterge {size}', ru='Удалить {size}', th='ลบ {size}',
  tr='{size} sil', vi='Xóa {size}', zh_Hans='删除 {size}',
  zh_Hant='刪除 {size}')
s('v2FreeCleanupsLeft',
  en='{count, plural, one{1 free cleanup left} other{{count} free cleanups left}}',
  ar='{count, plural, zero{لا توجد عمليات تنظيف مجانية} one{تبقّت عملية تنظيف مجانية واحدة} two{تبقّت عمليتا تنظيف مجانيتان} few{تبقّت {count} عمليات تنظيف مجانية} many{تبقّت {count} عملية تنظيف مجانية} other{تبقّت {count} عملية تنظيف مجانية}}',
  de='{count, plural, one{Noch 1 kostenlose Bereinigung} other{Noch {count} kostenlose Bereinigungen}}',
  es='{count, plural, one{Te queda 1 limpieza gratis} other{Te quedan {count} limpiezas gratis}}',
  fr='{count, plural, one{{count} nettoyage gratuit restant} other{{count} nettoyages gratuits restants}}',
  he='{count, plural, one{נותר ניקוי חינמי אחד} two{נותרו שני ניקויים חינמיים} other{נותרו {count} ניקויים חינמיים}}',
  id='{count, plural, other{Sisa {count} pembersihan gratis}}',
  it='{count, plural, one{Ti resta 1 pulizia gratuita} other{Ti restano {count} pulizie gratuite}}',
  ja='{count, plural, other{無料クリーンアップ残り{count}回}}',
  ko='{count, plural, other{무료 정리 {count}회 남음}}',
  pl='{count, plural, one{Zostało {count} darmowe czyszczenie} few{Zostały {count} darmowe czyszczenia} many{Zostało {count} darmowych czyszczeń} other{Zostało {count} darmowego czyszczenia}}',
  pt='{count, plural, one{Resta 1 limpeza grátis} other{Restam {count} limpezas grátis}}',
  ro='{count, plural, one{Ți-a rămas 1 curățare gratuită} few{Ți-au rămas {count} curățări gratuite} other{Ți-au rămas {count} de curățări gratuite}}',
  ru='{count, plural, one{Осталась {count} бесплатная очистка} few{Осталось {count} бесплатные очистки} many{Осталось {count} бесплатных очисток} other{Осталось {count} бесплатной очистки}}',
  th='{count, plural, other{เหลือการล้างฟรี {count} ครั้ง}}',
  tr='{count, plural, other{{count} ücretsiz temizlik hakkı kaldı}}',
  vi='{count, plural, other{Còn {count} lượt dọn miễn phí}}',
  zh_Hans='{count, plural, other{还剩 {count} 次免费清理}}',
  zh_Hant='{count, plural, other{還剩 {count} 次免費清理}}')

# ── Home ──
s('v2SpaceToClean', en='Space to Clean', ar='مساحة قابلة للتنظيف',
  de='Freizugebender Speicher', es='Espacio para limpiar',
  fr='Espace à libérer', he='מקום לניקוי', id='Ruang untuk dibersihkan',
  it='Spazio da liberare', ja='削除できる容量', ko='정리 가능한 공간',
  pl='Miejsce do zwolnienia', pt='Espaço a libertar',
  ro='Spațiu de eliberat', ru='Можно освободить', th='พื้นที่ที่ล้างได้',
  tr='Temizlenebilir alan', vi='Dung lượng có thể dọn',
  zh_Hans='可清理空间', zh_Hant='可清理空間')
s('v2StorageUsedOf', en='{used} of {total} used',
  ar='مستخدم {used} من {total}', de='{used} von {total} belegt',
  es='{used} de {total} usados', fr='{used} utilisés sur {total}',
  he='{used} מתוך {total} בשימוש', id='{used} dari {total} terpakai',
  it='{used} di {total} utilizzati', ja='{total}中{used}使用済み',
  ko='{total} 중 {used} 사용', pl='Zajęte {used} z {total}',
  pt='{used} de {total} usados', ro='{used} din {total} folosiți',
  ru='Занято {used} из {total}', th='ใช้ไป {used} จาก {total}',
  tr='{total} alanın {used} kadarı dolu', vi='Đã dùng {used} / {total}',
  zh_Hans='已使用 {used} / {total}', zh_Hant='已使用 {used} / {total}')
s('v2OptimizeTitle', en='Optimize Storage', ar='تحسين التخزين',
  de='Speicher optimieren', es='Optimizar almacenamiento',
  fr='Optimiser le stockage', he='אופטימיזציית אחסון',
  id='Optimalkan penyimpanan', it='Ottimizza spazio',
  ja='ストレージを最適化', ko='저장 공간 최적화', pl='Optymalizuj pamięć',
  pt='Otimizar armazenamento', ro='Optimizează spațiul',
  ru='Оптимизировать память', th='ปรับพื้นที่จัดเก็บ',
  tr='Depolamayı optimize et', vi='Tối ưu dung lượng',
  zh_Hans='优化存储空间', zh_Hant='最佳化儲存空間')
s('v2OptimizeSubtitle', en='Free up space from your files quickly',
  ar='حرّر المساحة من ملفاتك بسرعة', de='Schnell Speicherplatz freigeben',
  es='Libera espacio de tus archivos rápidamente',
  fr='Libérez vite de l’espace', he='פנו מקום מהקבצים במהירות',
  id='Kosongkan ruang dari file Anda dengan cepat',
  it='Libera spazio velocemente', ja='ファイルからすばやく空き容量を確保',
  ko='파일에서 빠르게 공간 확보', pl='Szybko zwolnij miejsce',
  pt='Liberte espaço rapidamente', ro='Eliberează rapid spațiu',
  ru='Быстро освободите место', th='เพิ่มพื้นที่ว่างได้อย่างรวดเร็ว',
  tr='Dosyalarınızdan hızla yer açın', vi='Giải phóng dung lượng nhanh chóng',
  zh_Hans='快速释放文件占用的空间', zh_Hant='快速釋放檔案佔用的空間')
s('v2Scanning', en='Scanning your library…', ar='جارٍ فحص مكتبتك…',
  de='Mediathek wird durchsucht…', es='Analizando tu biblioteca…',
  fr='Analyse de votre photothèque…', he='סורקים את הספרייה…',
  id='Memindai pustaka Anda…', it='Analisi della libreria…',
  ja='ライブラリをスキャン中…', ko='보관함을 스캔하는 중…',
  pl='Skanowanie biblioteki…', pt='A analisar a biblioteca…',
  ro='Se scanează biblioteca…', ru='Сканирование медиатеки…',
  th='กำลังสแกนคลังภาพ…', tr='Arşiviniz taranıyor…',
  vi='Đang quét thư viện…', zh_Hans='正在扫描图库…', zh_Hant='正在掃描圖庫…')
s('v2ScanningCount', en='{done} / {total}', ar='{done} / {total}',
  de='{done} / {total}', es='{done} / {total}', fr='{done} / {total}',
  he='{done} / {total}', id='{done} / {total}', it='{done} / {total}',
  ja='{done} / {total}', ko='{done} / {total}', pl='{done} / {total}',
  pt='{done} / {total}', ro='{done} / {total}', ru='{done} / {total}',
  th='{done} / {total}', tr='{done} / {total}', vi='{done} / {total}',
  zh_Hans='{done} / {total}', zh_Hant='{done} / {total}')
s('v2CheckingDuplicates', en='Checking duplicates…',
  ar='جارٍ التحقق من المكررات…', de='Duplikate werden geprüft…',
  es='Buscando duplicados…', fr='Vérification des doublons…',
  he='בודקים כפילויות…', id='Memeriksa duplikat…',
  it='Controllo dei duplicati…', ja='重複を確認中…', ko='중복 확인 중…',
  pl='Sprawdzanie duplikatów…', pt='A verificar duplicados…',
  ro='Se verifică duplicatele…', ru='Проверка дубликатов…',
  th='กำลังตรวจรูปซ้ำ…', tr='Kopyalar kontrol ediliyor…',
  vi='Đang kiểm tra ảnh trùng…', zh_Hans='正在检查重复照片…',
  zh_Hant='正在檢查重複照片…')
s('v2ScanStart', en='Scan my photos', ar='افحص صوري', de='Fotos scannen',
  es='Analizar mis fotos', fr='Analyser mes photos', he='סריקת התמונות',
  id='Pindai foto saya', it='Analizza le mie foto', ja='写真をスキャン',
  ko='사진 스캔하기', pl='Skanuj zdjęcia', pt='Analisar as minhas fotos',
  ro='Scanează pozele', ru='Сканировать фото', th='สแกนรูปของฉัน',
  tr='Fotoğraflarımı tara', vi='Quét ảnh của tôi', zh_Hans='扫描我的照片',
  zh_Hant='掃描我的照片')
s('v2PermissionTitle', en='Allow access to Photos', ar='اسمح بالوصول إلى الصور',
  de='Zugriff auf Fotos erlauben', es='Permitir acceso a Fotos',
  fr="Autoriser l'accès aux Photos", he='אפשרו גישה לתמונות',
  id='Izinkan akses ke Foto', it="Consenti l'accesso a Foto",
  ja='写真へのアクセスを許可', ko='사진 접근 허용',
  pl='Zezwól na dostęp do Zdjęć', pt='Permitir acesso às Fotos',
  ro='Permite accesul la Poze', ru='Разрешите доступ к Фото',
  th='อนุญาตให้เข้าถึงรูปภาพ', tr='Fotoğraflara erişime izin verin',
  vi='Cho phép truy cập Ảnh', zh_Hans='允许访问照片', zh_Hant='允許存取照片')
s('v2PermissionBody',
  en='{appName} needs access to your photos to find duplicates and free up storage. Your photos stay on your device.',
  ar='يحتاج {appName} إلى الوصول إلى صورك للعثور على المكررات وتحرير المساحة. تبقى صورك على جهازك.',
  de='{appName} braucht Zugriff auf deine Fotos, um Duplikate zu finden und Speicher freizugeben. Deine Fotos bleiben auf deinem Gerät.',
  es='{appName} necesita acceder a tus fotos para encontrar duplicados y liberar espacio. Tus fotos se quedan en tu dispositivo.',
  fr='{appName} a besoin d’accéder à vos photos pour trouver les doublons et libérer de l’espace. Vos photos restent sur votre appareil.',
  he='{appName} צריכה גישה לתמונות כדי למצוא כפילויות ולפנות מקום. התמונות נשארות במכשיר שלכם.',
  id='{appName} memerlukan akses ke foto Anda untuk menemukan duplikat dan mengosongkan ruang. Foto Anda tetap di perangkat Anda.',
  it='{appName} ha bisogno di accedere alle foto per trovare i duplicati e liberare spazio. Le tue foto restano sul dispositivo.',
  ja='{appName}は重複を見つけて空き容量を増やすために写真へのアクセスが必要です。写真はデバイスから外に出ません。',
  ko='{appName}이(가) 중복 사진을 찾고 공간을 확보하려면 사진 접근 권한이 필요합니다. 사진은 기기에만 저장됩니다.',
  pl='{appName} potrzebuje dostępu do zdjęć, aby znaleźć duplikaty i zwolnić miejsce. Zdjęcia pozostają na urządzeniu.',
  pt='{appName} precisa de acesso às fotos para encontrar duplicados e libertar espaço. As fotos ficam no seu dispositivo.',
  ro='{appName} are nevoie de acces la poze pentru a găsi duplicatele și a elibera spațiu. Pozele rămân pe dispozitiv.',
  ru='{appName} нужен доступ к фото, чтобы найти дубликаты и освободить место. Фото остаются на вашем устройстве.',
  th='{appName} ต้องเข้าถึงรูปภาพเพื่อค้นหารูปซ้ำและเพิ่มพื้นที่ว่าง รูปของคุณจะอยู่บนอุปกรณ์เท่านั้น',
  tr='{appName}, kopyaları bulup yer açmak için fotoğraflarınıza erişmelidir. Fotoğraflarınız cihazınızda kalır.',
  vi='{appName} cần quyền truy cập ảnh để tìm ảnh trùng và giải phóng dung lượng. Ảnh của bạn luôn nằm trên thiết bị.',
  zh_Hans='{appName} 需要访问你的照片来查找重复项并释放空间。照片始终保留在你的设备上。',
  zh_Hant='{appName} 需要存取你的照片來找出重複項並釋放空間。照片始終保留在你的裝置上。')
s('v2OpenSettings', en='Open Settings', ar='فتح الإعدادات',
  de='Einstellungen öffnen', es='Abrir Ajustes', fr='Ouvrir Réglages',
  he='פתיחת ההגדרות', id='Buka Pengaturan', it='Apri Impostazioni',
  ja='設定を開く', ko='설정 열기', pl='Otwórz Ustawienia',
  pt='Abrir Definições', ro='Deschide Setări', ru='Открыть Настройки',
  th='เปิดการตั้งค่า', tr='Ayarları aç', vi='Mở Cài đặt',
  zh_Hans='打开设置', zh_Hant='打開設定')

s('v2ScanPaused', en='Scan paused', ar='الفحص متوقف مؤقتًا',
  de='Scan pausiert', es='Análisis en pausa', fr='Analyse en pause',
  he='הסריקה מושהית', id='Pemindaian dijeda', it='Analisi in pausa',
  ja='スキャンを一時停止中', ko='스캔 일시 중지됨', pl='Skanowanie wstrzymane',
  pt='Análise em pausa', ro='Scanare întreruptă', ru='Сканирование на паузе',
  th='หยุดสแกนชั่วคราว', tr='Tarama duraklatıldı', vi='Đã tạm dừng quét',
  zh_Hans='扫描已暂停', zh_Hant='掃描已暫停')
s('v2ContinueScan', en='Continue', ar='متابعة', de='Fortsetzen',
  es='Continuar', fr='Reprendre', he='המשך', id='Lanjutkan',
  it='Riprendi', ja='再開', ko='계속하기', pl='Wznów', pt='Continuar',
  ro='Continuă', ru='Продолжить', th='สแกนต่อ', tr='Devam et',
  vi='Tiếp tục', zh_Hans='继续扫描', zh_Hant='繼續掃描')
s('v2PauseScan', en='Pause scan', ar='إيقاف الفحص مؤقتًا',
  de='Scan pausieren', es='Pausar análisis', fr='Mettre en pause',
  he='השהיית הסריקה', id='Jeda pemindaian', it='Metti in pausa',
  ja='スキャンを一時停止', ko='스캔 일시 중지', pl='Wstrzymaj skanowanie',
  pt='Pausar análise', ro='Întrerupe scanarea', ru='Приостановить',
  th='หยุดสแกนชั่วคราว', tr='Taramayı duraklat', vi='Tạm dừng quét',
  zh_Hans='暂停扫描', zh_Hant='暫停掃描')

# ── Category intro ──
s('v2IntroLeft', en='Left', ar='يسارًا', de='Links', es='Izquierda',
  fr='À gauche', he='שמאלה', id='Kiri', it='Sinistra', ja='左へ',
  ko='왼쪽', pl='W lewo', pt='Esquerda', ro='Stânga', ru='Влево',
  th='ปัดซ้าย', tr='Sola', vi='Trái', zh_Hans='向左', zh_Hant='向左')
s('v2IntroToDelete', en='to Delete', ar='للحذف', de='zum Löschen',
  es='para eliminar', fr='pour supprimer', he='למחיקה', id='untuk hapus',
  it='per eliminare', ja='で削除', ko='삭제', pl='usuń', pt='para apagar',
  ro='pentru ștergere', ru='удалить', th='เพื่อลบ', tr='sil',
  vi='để xóa', zh_Hans='删除', zh_Hant='刪除')
s('v2IntroRight', en='Right', ar='يمينًا', de='Rechts', es='Derecha',
  fr='À droite', he='ימינה', id='Kanan', it='Destra', ja='右へ',
  ko='오른쪽', pl='W prawo', pt='Direita', ro='Dreapta', ru='Вправо',
  th='ปัดขวา', tr='Sağa', vi='Phải', zh_Hans='向右', zh_Hant='向右')
s('v2IntroToKeep', en='to Keep', ar='للاحتفاظ', de='zum Behalten',
  es='para conservar', fr='pour garder', he='לשמירה', id='untuk simpan',
  it='per tenere', ja='で残す', ko='보관', pl='zachowaj', pt='para manter',
  ro='pentru păstrare', ru='оставить', th='เพื่อเก็บ', tr='sakla',
  vi='để giữ', zh_Hans='保留', zh_Hant='保留')
s('v2LetsGo', en="Let's go", ar='لنبدأ', de='Los geht’s', es='Vamos',
  fr="C'est parti", he='קדימה', id='Ayo mulai', it='Iniziamo',
  ja='はじめる', ko='시작하기', pl='Zaczynamy', pt='Vamos lá',
  ro='Să începem', ru='Начать', th='เริ่มเลย', tr='Başlayalım',
  vi='Bắt đầu', zh_Hans='开始吧', zh_Hant='開始吧')
s('v2IntroSimilars',
  en='Similar shots are grouped together. We keep the best one and select the rest for you.',
  ar='نجمع اللقطات المتشابهة معًا. نحتفظ بالأفضل ونحدد البقية لك.',
  de='Ähnliche Aufnahmen werden gruppiert. Wir behalten die beste und wählen den Rest für dich aus.',
  es='Agrupamos las fotos parecidas. Conservamos la mejor y seleccionamos el resto por ti.',
  fr='Les photos similaires sont regroupées. Nous gardons la meilleure et sélectionnons les autres pour vous.',
  he='תמונות דומות מקובצות יחד. אנחנו שומרים את הטובה ביותר ובוחרים עבורכם את השאר.',
  id='Foto yang mirip dikelompokkan. Kami menyimpan yang terbaik dan memilih sisanya untuk Anda.',
  it='Gli scatti simili sono raggruppati. Teniamo il migliore e selezioniamo gli altri per te.',
  ja='似た写真をまとめて表示します。ベストな1枚を残し、残りを選択しておきます。',
  ko='비슷한 사진을 묶어 보여 드립니다. 가장 좋은 사진은 남기고 나머지는 자동으로 선택합니다.',
  pl='Podobne ujęcia są pogrupowane. Zachowujemy najlepsze, a resztę zaznaczamy za Ciebie.',
  pt='As fotos parecidas ficam agrupadas. Mantemos a melhor e selecionamos as restantes por si.',
  ro='Pozele asemănătoare sunt grupate. O păstrăm pe cea mai bună și le selectăm pe celelalte pentru tine.',
  ru='Похожие снимки собраны в группы. Мы оставляем лучший и выбираем остальные за вас.',
  th='รูปที่คล้ายกันจะถูกจัดกลุ่มไว้ เราเก็บรูปที่ดีที่สุดและเลือกที่เหลือให้คุณ',
  tr='Benzer kareler gruplanır. En iyisini tutar, kalanları sizin için seçeriz.',
  vi='Ảnh tương tự được gom nhóm. Chúng tôi giữ ảnh đẹp nhất và chọn sẵn những ảnh còn lại.',
  zh_Hans='相似照片会分组显示。我们保留最佳的一张，其余的已帮你选好。',
  zh_Hant='相似照片會分組顯示。我們保留最佳的一張，其餘的已幫你選好。')
s('v2IntroDuplicates',
  en='Exact copies of the same photo. Keep one and delete the rest in one tap.',
  ar='نسخ مطابقة من الصورة نفسها. احتفظ بواحدة واحذف البقية بلمسة واحدة.',
  de='Exakte Kopien desselben Fotos. Behalte eins und lösche den Rest mit einem Tipp.',
  es='Copias exactas de la misma foto. Conserva una y elimina el resto con un toque.',
  fr='Copies exactes d’une même photo. Gardez-en une et supprimez le reste en un geste.',
  he='עותקים זהים של אותה תמונה. שמרו אחת ומחקו את השאר בהקשה אחת.',
  id='Salinan persis dari foto yang sama. Simpan satu dan hapus sisanya sekali ketuk.',
  it='Copie identiche della stessa foto. Tienine una ed elimina le altre con un tocco.',
  ja='まったく同じ写真のコピーです。1枚残して、残りをワンタップで削除できます。',
  ko='같은 사진의 완전한 복사본입니다. 하나만 남기고 나머지는 한 번에 삭제하세요.',
  pl='Dokładne kopie tego samego zdjęcia. Zachowaj jedno, a resztę usuń jednym dotknięciem.',
  pt='Cópias exatas da mesma foto. Mantenha uma e apague as restantes com um toque.',
  ro='Copii identice ale aceleiași poze. Păstrează una și șterge restul dintr-o atingere.',
  ru='Точные копии одного снимка. Оставьте один, а остальные удалите одним касанием.',
  th='สำเนาของรูปเดียวกันทุกประการ เก็บไว้หนึ่งรูปแล้วลบที่เหลือในแตะเดียว',
  tr='Aynı fotoğrafın birebir kopyaları. Birini tutun, kalanını tek dokunuşla silin.',
  vi='Các bản sao giống hệt của cùng một ảnh. Giữ một ảnh và xóa phần còn lại chỉ với một chạm.',
  zh_Hans='完全相同的照片副本。保留一张，其余一键删除。',
  zh_Hant='完全相同的照片副本。保留一張，其餘一鍵刪除。')
s('v2IntroVideos',
  en='Review all your videos. Sort them by size or date to see the ones that take the most space.',
  ar='راجع كل فيديوهاتك. رتّبها حسب الحجم أو التاريخ لترى الأكثر استهلاكًا للمساحة.',
  de='Sieh dir alle Videos an. Sortiere nach Größe oder Datum, um die größten Speicherfresser zu finden.',
  es='Revisa todos tus vídeos. Ordénalos por tamaño o fecha para ver los que más ocupan.',
  fr='Passez en revue vos vidéos. Triez-les par taille ou par date pour repérer les plus lourdes.',
  he='עברו על כל הסרטונים. מיינו לפי גודל או תאריך כדי לראות מה תופס הכי הרבה מקום.',
  id='Tinjau semua video Anda. Urutkan menurut ukuran atau tanggal untuk melihat yang paling besar.',
  it='Rivedi tutti i video. Ordinali per dimensione o data per vedere quelli che occupano più spazio.',
  ja='すべてのビデオを確認できます。サイズや日付で並べ替えて、容量の大きいものを見つけましょう。',
  ko='모든 동영상을 확인하세요. 크기나 날짜로 정렬해 공간을 많이 차지하는 동영상을 찾을 수 있습니다.',
  pl='Przejrzyj wszystkie filmy. Posortuj je według rozmiaru lub daty, by znaleźć te największe.',
  pt='Reveja todos os vídeos. Ordene por tamanho ou data para ver os que ocupam mais espaço.',
  ro='Revizuiește toate clipurile. Sortează-le după mărime sau dată ca să le vezi pe cele mai mari.',
  ru='Просмотрите все видео. Отсортируйте по размеру или дате, чтобы найти самые тяжёлые.',
  th='ดูวิดีโอทั้งหมดของคุณ เรียงตามขนาดหรือวันที่เพื่อดูว่าวิดีโอไหนใช้พื้นที่มากที่สุด',
  tr='Tüm videolarınızı inceleyin. En çok yer kaplayanları görmek için boyuta veya tarihe göre sıralayın.',
  vi='Xem lại tất cả video. Sắp xếp theo dung lượng hoặc ngày để thấy video chiếm nhiều chỗ nhất.',
  zh_Hans='查看所有视频。按大小或日期排序，找出最占空间的视频。',
  zh_Hant='查看所有影片。依大小或日期排序，找出最佔空間的影片。')
s('v2IntroScreenshots',
  en='Old screenshots pile up fast. Swipe through them and clear the ones you no longer need.',
  ar='تتراكم لقطات الشاشة القديمة بسرعة. تصفحها واحذف ما لم تعد تحتاجه.',
  de='Alte Bildschirmfotos sammeln sich schnell. Wische durch und entferne, was du nicht mehr brauchst.',
  es='Las capturas antiguas se acumulan rápido. Repásalas y borra las que ya no necesitas.',
  fr='Les vieilles captures s’accumulent vite. Faites-les défiler et supprimez celles devenues inutiles.',
  he='צילומי מסך ישנים מצטברים מהר. דפדפו ביניהם ומחקו את מה שכבר לא צריך.',
  id='Tangkapan layar lama cepat menumpuk. Geser dan hapus yang tidak lagi Anda perlukan.',
  it='Gli screenshot si accumulano in fretta. Scorrili ed elimina quelli che non ti servono più.',
  ja='古いスクリーンショットはすぐにたまります。スワイプして不要なものを削除しましょう。',
  ko='오래된 스크린샷은 금방 쌓입니다. 넘겨 보면서 필요 없는 것을 정리하세요.',
  pl='Stare zrzuty ekranu szybko się gromadzą. Przejrzyj je i usuń niepotrzebne.',
  pt='As capturas antigas acumulam-se depressa. Percorra-as e apague as que já não precisa.',
  ro='Capturile vechi se adună repede. Parcurge-le și șterge-le pe cele de care nu mai ai nevoie.',
  ru='Старые скриншоты быстро копятся. Пролистайте их и удалите ненужные.',
  th='ภาพหน้าจอเก่าสะสมเร็วมาก ปัดดูแล้วลบภาพที่ไม่ต้องการแล้ว',
  tr='Eski ekran görüntüleri hızla birikir. Kaydırarak göz atın, gerekmeyenleri silin.',
  vi='Ảnh chụp màn hình cũ tích tụ rất nhanh. Vuốt qua và xóa những ảnh không còn cần.',
  zh_Hans='旧截图很快就会堆积。滑动浏览，清掉不再需要的截图。',
  zh_Hant='舊截圖很快就會堆積。滑動瀏覽，清掉不再需要的截圖。')
s('v2IntroBlurred',
  en="Blurry and out-of-focus shots you probably don't want to keep.",
  ar='لقطات ضبابية وغير واضحة لا ترغب غالبًا في الاحتفاظ بها.',
  de='Verwackelte und unscharfe Aufnahmen, die du wahrscheinlich nicht behalten willst.',
  es='Fotos borrosas o desenfocadas que probablemente no quieras conservar.',
  fr='Des photos floues que vous ne voulez sans doute pas garder.',
  he='תמונות מטושטשות ולא ממוקדות שכנראה לא תרצו לשמור.',
  id='Foto buram dan tidak fokus yang mungkin tidak ingin Anda simpan.',
  it='Scatti mossi e fuori fuoco che probabilmente non vuoi tenere.',
  ja='ブレたりピンぼけしたりして、残す必要がなさそうな写真です。',
  ko='흔들리거나 초점이 맞지 않아 남길 필요가 없을 사진입니다.',
  pl='Rozmazane i nieostre zdjęcia, których pewnie nie chcesz zachować.',
  pt='Fotos tremidas e desfocadas que provavelmente não quer guardar.',
  ro='Poze mișcate sau neclare pe care probabil nu vrei să le păstrezi.',
  ru='Смазанные и нечёткие снимки, которые вряд ли стоит хранить.',
  th='รูปที่เบลอหรือไม่ชัดซึ่งคุณอาจไม่อยากเก็บไว้',
  tr='Muhtemelen saklamak istemeyeceğiniz bulanık ve odak dışı kareler.',
  vi='Những ảnh mờ, lệch nét mà bạn có lẽ không muốn giữ.',
  zh_Hans='模糊、失焦、你大概不想留下的照片。',
  zh_Hant='模糊、失焦、你大概不想留下的照片。')
s('v2IntroLarge',
  en='Your biggest photos and videos. Deleting a few of them frees the most space.',
  ar='أكبر صورك وفيديوهاتك. حذف القليل منها يحرر أكبر مساحة.',
  de='Deine größten Fotos und Videos. Schon wenige davon zu löschen, bringt am meisten Platz.',
  es='Tus fotos y vídeos más pesados. Eliminar unos pocos libera mucho espacio.',
  fr='Vos plus gros fichiers. En supprimer quelques-uns libère le plus d’espace.',
  he='התמונות והסרטונים הגדולים ביותר. מחיקה של כמה מהם מפנה הכי הרבה מקום.',
  id='Foto dan video terbesar Anda. Menghapus beberapa saja membebaskan ruang paling banyak.',
  it='Le foto e i video più pesanti. Eliminarne alcuni libera più spazio.',
  ja='最も大きな写真とビデオです。いくつか削除するだけで大きく空きます。',
  ko='용량이 가장 큰 사진과 동영상입니다. 몇 개만 지워도 공간이 크게 늘어납니다.',
  pl='Twoje największe zdjęcia i filmy. Usunięcie kilku zwalnia najwięcej miejsca.',
  pt='As suas fotos e vídeos maiores. Apagar alguns liberta mais espaço.',
  ro='Cele mai mari poze și clipuri. Ștergând câteva eliberezi cel mai mult spațiu.',
  ru='Самые большие фото и видео. Удалив несколько, вы освободите больше всего места.',
  th='รูปและวิดีโอที่ใหญ่ที่สุดของคุณ ลบเพียงไม่กี่รายการก็ได้พื้นที่คืนมามาก',
  tr='En büyük fotoğraf ve videolarınız. Birkaçını silmek en çok yeri açar.',
  vi='Những ảnh và video lớn nhất. Chỉ cần xóa vài tệp là giải phóng nhiều dung lượng nhất.',
  zh_Hans='最大的照片和视频。删掉几个就能释放最多空间。',
  zh_Hant='最大的照片和影片。刪掉幾個就能釋放最多空間。')
s('v2IntroOther',
  en="Photos that don't belong to any category. Sort them by size or date and say goodbye to the ones you don't need.",
  ar='صور لا تنتمي إلى أي فئة. رتّبها حسب الحجم أو التاريخ وودّع ما لا تحتاجه.',
  de='Fotos, die in keine Kategorie passen. Sortiere nach Größe oder Datum und trenne dich von Unnötigem.',
  es='Fotos que no pertenecen a ninguna categoría. Ordénalas por tamaño o fecha y despídete de las que sobran.',
  fr='Les photos hors catégorie. Triez-les par taille ou par date et dites adieu à l’inutile.',
  he='תמונות שלא שייכות לאף קטגוריה. מיינו לפי גודל או תאריך ונפרדו ממה שמיותר.',
  id='Foto yang tidak termasuk kategori apa pun. Urutkan menurut ukuran atau tanggal dan hapus yang tidak perlu.',
  it='Foto che non rientrano in nessuna categoria. Ordinale per dimensione o data e di’ addio a quelle inutili.',
  ja='どのカテゴリにも入らない写真です。サイズや日付で並べ替えて、不要なものを整理しましょう。',
  ko='어느 카테고리에도 속하지 않는 사진입니다. 크기나 날짜로 정렬해 필요 없는 사진을 정리하세요.',
  pl='Zdjęcia spoza kategorii. Posortuj je według rozmiaru lub daty i pożegnaj niepotrzebne.',
  pt='Fotos que não pertencem a nenhuma categoria. Ordene por tamanho ou data e despeça-se das desnecessárias.',
  ro='Poze care nu aparțin niciunei categorii. Sortează-le după mărime sau dată și scapă de cele inutile.',
  ru='Фото вне категорий. Отсортируйте по размеру или дате и попрощайтесь с лишним.',
  th='รูปที่ไม่อยู่ในหมวดใดเลย เรียงตามขนาดหรือวันที่แล้วลบรูปที่ไม่จำเป็น',
  tr='Hiçbir kategoriye girmeyen fotoğraflar. Boyuta veya tarihe göre sıralayın, gereksizlere veda edin.',
  vi='Những ảnh không thuộc danh mục nào. Sắp xếp theo dung lượng hoặc ngày và tạm biệt ảnh không cần.',
  zh_Hans='不属于任何分类的照片。按大小或日期排序，和不需要的照片说再见。',
  zh_Hant='不屬於任何分類的照片。依大小或日期排序，和不需要的照片說再見。')
s('v2IntroOptimize',
  en='Finds duplicate and similar photos, keeps the best ones and selects the rest. Free up space in seconds.',
  ar='يعثر على الصور المكررة والمتشابهة، ويحتفظ بالأفضل ويحدد البقية. حرّر المساحة في ثوانٍ.',
  de='Findet doppelte und ähnliche Fotos, behält die besten und wählt den Rest aus. Platz in Sekunden.',
  es='Encuentra fotos duplicadas y parecidas, conserva las mejores y selecciona el resto. Libera espacio en segundos.',
  fr='Trouve les doublons et photos similaires, garde les meilleures et sélectionne le reste. De l’espace en quelques secondes.',
  he='מוצא תמונות כפולות ודומות, שומר את הטובות ובוחר את השאר. מפנים מקום בשניות.',
  id='Menemukan foto duplikat dan mirip, menyimpan yang terbaik, dan memilih sisanya. Kosongkan ruang dalam hitungan detik.',
  it='Trova foto duplicate e simili, tiene le migliori e seleziona le altre. Libera spazio in pochi secondi.',
  ja='重複写真と類似写真を見つけ、ベストを残して残りを選択します。数秒で容量を確保。',
  ko='중복·유사 사진을 찾아 가장 좋은 사진은 남기고 나머지를 선택합니다. 몇 초 만에 공간을 확보하세요.',
  pl='Znajduje duplikaty i podobne zdjęcia, zachowuje najlepsze i zaznacza resztę. Miejsce w kilka sekund.',
  pt='Encontra fotos duplicadas e parecidas, mantém as melhores e seleciona as restantes. Espaço em segundos.',
  ro='Găsește pozele duplicate și similare, le păstrează pe cele mai bune și le selectează pe restul. Spațiu în câteva secunde.',
  ru='Находит дубликаты и похожие фото, оставляет лучшие и выбирает остальные. Место — за секунды.',
  th='ค้นหารูปซ้ำและรูปที่คล้ายกัน เก็บรูปที่ดีที่สุดและเลือกที่เหลือให้ เพิ่มพื้นที่ได้ในไม่กี่วินาที',
  tr='Kopya ve benzer fotoğrafları bulur, en iyilerini tutar, kalanları seçer. Saniyeler içinde yer açın.',
  vi='Tìm ảnh trùng và ảnh tương tự, giữ ảnh đẹp nhất và chọn sẵn phần còn lại. Giải phóng dung lượng trong vài giây.',
  zh_Hans='找出重复和相似照片，保留最佳的，其余自动选好。几秒钟释放空间。',
  zh_Hant='找出重複和相似照片，保留最佳的，其餘自動選好。幾秒鐘釋放空間。')

# ── Grid ──
s('v2SortLargest', en='Largest', ar='الأكبر', de='Größte', es='Más grandes',
  fr='Plus lourdes', he='הגדולים', id='Terbesar', it='Più grandi',
  ja='サイズ順', ko='큰 순서', pl='Największe', pt='Maiores',
  ro='Cele mai mari', ru='Крупные', th='ใหญ่สุด', tr='En büyük',
  vi='Lớn nhất', zh_Hans='最大', zh_Hant='最大')
s('v2SortNewest', en='Newest', ar='الأحدث', de='Neueste', es='Más recientes',
  fr='Plus récentes', he='החדשים', id='Terbaru', it='Più recenti',
  ja='新しい順', ko='최신순', pl='Najnowsze', pt='Mais recentes',
  ro='Cele mai noi', ru='Новые', th='ใหม่สุด', tr='En yeni',
  vi='Mới nhất', zh_Hans='最新', zh_Hant='最新')
s('v2EmptyCategory', en='Nothing to clean here', ar='لا يوجد ما يُنظَّف هنا',
  de='Hier gibt es nichts zu bereinigen', es='No hay nada que limpiar',
  fr='Rien à nettoyer ici', he='אין כאן מה לנקות',
  id='Tidak ada yang perlu dibersihkan', it='Niente da pulire qui',
  ja='整理するものはありません', ko='정리할 항목이 없습니다',
  pl='Nie ma tu nic do sprzątania', pt='Nada para limpar aqui',
  ro='Nimic de curățat aici', ru='Здесь нечего чистить',
  th='ไม่มีอะไรให้ล้าง', tr='Burada temizlenecek bir şey yok',
  vi='Không có gì để dọn', zh_Hans='这里没有需要清理的内容',
  zh_Hant='這裡沒有需要清理的內容')
s('v2EmptyCategoryBody', en='This category is already clean.',
  ar='هذه الفئة نظيفة بالفعل.', de='Diese Kategorie ist schon aufgeräumt.',
  es='Esta categoría ya está limpia.', fr='Cette catégorie est déjà propre.',
  he='הקטגוריה הזו כבר נקייה.', id='Kategori ini sudah bersih.',
  it='Questa categoria è già in ordine.', ja='このカテゴリはすでに整理済みです。',
  ko='이 카테고리는 이미 깔끔합니다.', pl='Ta kategoria jest już uporządkowana.',
  pt='Esta categoria já está limpa.', ro='Categoria aceasta e deja curată.',
  ru='В этой категории уже чисто.', th='หมวดนี้สะอาดอยู่แล้ว',
  tr='Bu kategori zaten temiz.', vi='Danh mục này đã gọn gàng.',
  zh_Hans='这个分类已经很干净了。', zh_Hant='這個分類已經很乾淨了。')
s('v2VideoCompress', en='Video Compress', ar='ضغط الفيديو',
  de='Videos komprimieren', es='Comprimir vídeo', fr='Compresser les vidéos',
  he='דחיסת סרטונים', id='Kompres video', it='Comprimi video',
  ja='ビデオ圧縮', ko='동영상 압축', pl='Kompresja filmów',
  pt='Comprimir vídeos', ro='Comprimă clipuri', ru='Сжатие видео',
  th='บีบอัดวิดีโอ', tr='Video sıkıştır', vi='Nén video',
  zh_Hans='视频压缩', zh_Hant='影片壓縮')
s('v2VideoCompressSubtitle', en='Tap to start the process',
  ar='انقر للبدء', de='Tippe, um zu starten', es='Toca para empezar',
  fr='Touchez pour commencer', he='הקישו כדי להתחיל', id='Ketuk untuk mulai',
  it='Tocca per iniziare', ja='タップして開始', ko='탭하여 시작',
  pl='Dotknij, aby zacząć', pt='Toque para começar', ro='Atinge pentru a începe',
  ru='Нажмите, чтобы начать', th='แตะเพื่อเริ่ม', tr='Başlamak için dokunun',
  vi='Chạm để bắt đầu', zh_Hans='点按开始', zh_Hant='點一下開始')
s('v2VideoCompressBody',
  en='Compress videos into smaller copies to save storage.',
  ar='اضغط الفيديوهات إلى نسخ أصغر لتوفير المساحة.',
  de='Komprimiere Videos zu kleineren Kopien und spare Speicher.',
  es='Comprime vídeos en copias más pequeñas para ahorrar espacio.',
  fr='Compressez vos vidéos en copies plus légères pour gagner de l’espace.',
  he='דחסו סרטונים לעותקים קטנים יותר כדי לחסוך מקום.',
  id='Kompres video menjadi salinan lebih kecil untuk menghemat ruang.',
  it='Comprimi i video in copie più leggere per risparmiare spazio.',
  ja='ビデオを小さなコピーに圧縮して容量を節約します。',
  ko='동영상을 더 작은 사본으로 압축해 공간을 절약하세요.',
  pl='Kompresuj filmy do mniejszych kopii i oszczędzaj miejsce.',
  pt='Comprima vídeos em cópias mais pequenas para poupar espaço.',
  ro='Comprimă clipurile în copii mai mici ca să economisești spațiu.',
  ru='Сжимайте видео в копии поменьше, чтобы сэкономить место.',
  th='บีบอัดวิดีโอเป็นสำเนาที่เล็กลงเพื่อประหยัดพื้นที่',
  tr='Yer kazanmak için videoları daha küçük kopyalara sıkıştırın.',
  vi='Nén video thành bản sao nhỏ hơn để tiết kiệm dung lượng.',
  zh_Hans='把视频压缩成更小的副本，节省空间。',
  zh_Hant='把影片壓縮成更小的副本，節省空間。')

# ── Congratulations ──
s('v2CongratsTitle', en='Congratulations!', ar='تهانينا!',
  de='Glückwunsch!', es='¡Enhorabuena!', fr='Félicitations !',
  he='כל הכבוד!', id='Selamat!', it='Complimenti!', ja='おめでとうございます！',
  ko='축하합니다!', pl='Gratulacje!', pt='Parabéns!', ro='Felicitări!',
  ru='Поздравляем!', th='ยินดีด้วย!', tr='Tebrikler!', vi='Chúc mừng!',
  zh_Hans='恭喜！', zh_Hant='恭喜！')
s('v2CongratsDeleted', en='You have deleted', ar='لقد حذفت',
  de='Du hast gelöscht:', es='Has eliminado', fr='Vous avez supprimé',
  he='מחקתם', id='Anda telah menghapus', it='Hai eliminato',
  ja='削除した項目', ko='삭제한 항목', pl='Usunięto', pt='Apagou',
  ro='Ai șters', ru='Вы удалили', th='คุณลบไปแล้ว', tr='Sildiğiniz',
  vi='Bạn đã xóa', zh_Hans='你已删除', zh_Hant='你已刪除')
s('v2CongratsSaved',
  en='{minutes, plural, one{Saved about 1 minute} other{Saved about {minutes} minutes}}',
  ar='{minutes, plural, zero{وفّرت وقتًا} one{وفّرت نحو دقيقة} two{وفّرت نحو دقيقتين} few{وفّرت نحو {minutes} دقائق} many{وفّرت نحو {minutes} دقيقة} other{وفّرت نحو {minutes} دقيقة}}',
  de='{minutes, plural, one{Etwa 1 Minute gespart} other{Etwa {minutes} Minuten gespart}}',
  es='{minutes, plural, one{Has ahorrado 1 minuto aprox.} other{Has ahorrado unos {minutes} minutos}}',
  fr='{minutes, plural, one{Environ {minutes} minute gagnée} other{Environ {minutes} minutes gagnées}}',
  he='{minutes, plural, one{חסכתם כדקה} two{חסכתם כשתי דקות} other{חסכתם כ־{minutes} דקות}}',
  id='{minutes, plural, other{Menghemat sekitar {minutes} menit}}',
  it='{minutes, plural, one{Circa 1 minuto risparmiato} other{Circa {minutes} minuti risparmiati}}',
  ja='{minutes, plural, other{約{minutes}分を節約}}',
  ko='{minutes, plural, other{약 {minutes}분 절약}}',
  pl='{minutes, plural, one{Zaoszczędzono ok. {minutes} minutę} few{Zaoszczędzono ok. {minutes} minuty} many{Zaoszczędzono ok. {minutes} minut} other{Zaoszczędzono ok. {minutes} minuty}}',
  pt='{minutes, plural, one{Poupou cerca de 1 minuto} other{Poupou cerca de {minutes} minutos}}',
  ro='{minutes, plural, one{Ai economisit cam 1 minut} few{Ai economisit cam {minutes} minute} other{Ai economisit cam {minutes} de minute}}',
  ru='{minutes, plural, one{Сэкономлено около {minutes} минуты} few{Сэкономлено около {minutes} минут} many{Сэкономлено около {minutes} минут} other{Сэкономлено около {minutes} минуты}}',
  th='{minutes, plural, other{ประหยัดเวลาประมาณ {minutes} นาที}}',
  tr='{minutes, plural, other{Yaklaşık {minutes} dakika kazandınız}}',
  vi='{minutes, plural, other{Tiết kiệm khoảng {minutes} phút}}',
  zh_Hans='{minutes, plural, other{节省约 {minutes} 分钟}}',
  zh_Hant='{minutes, plural, other{節省約 {minutes} 分鐘}}')
s('v2CongratsUsing', en='using {appName}', ar='باستخدام {appName}',
  de='mit {appName}', es='con {appName}', fr='avec {appName}',
  he='בעזרת {appName}', id='dengan {appName}', it='con {appName}',
  ja='{appName}を使って', ko='{appName} 사용', pl='dzięki {appName}',
  pt='com {appName}', ro='cu {appName}', ru='с {appName}',
  th='ด้วย {appName}', tr='{appName} ile', vi='nhờ {appName}',
  zh_Hans='使用 {appName}', zh_Hant='使用 {appName}')
s('v2CongratsRecentlyDeleted',
  en='Empty the “Recently Deleted” album on your iPhone to free up {size}.',
  ar='أفرغ ألبوم «المحذوفة مؤخرًا» على جهازك لتحرير {size}.',
  de='Leere das Album „Zuletzt gelöscht“, um {size} freizugeben.',
  es='Vacía el álbum “Eliminado” de tu iPhone para liberar {size}.',
  fr='Videz l’album « Supprimés récemment » pour libérer {size}.',
  he='רוקנו את האלבום „נמחקו לאחרונה” כדי לפנות {size}.',
  id='Kosongkan album “Baru Dihapus” di iPhone Anda untuk membebaskan {size}.',
  it='Svuota l’album “Eliminati di recente” per liberare {size}.',
  ja='「最近削除した項目」を空にすると{size}が解放されます。',
  ko='"최근 삭제된 항목" 앨범을 비우면 {size}가 확보됩니다.',
  pl='Opróżnij album „Ostatnio usunięte”, aby zwolnić {size}.',
  pt='Esvazie o álbum “Apagados” no iPhone para libertar {size}.',
  ro='Golește albumul „Șterse recent” ca să eliberezi {size}.',
  ru='Очистите альбом «Недавно удалённые», чтобы освободить {size}.',
  th='ล้างอัลบั้ม "ที่เพิ่งลบ" บน iPhone เพื่อเพิ่มพื้นที่ {size}',
  tr='{size} yer açmak için iPhone’unuzdaki “Son Silinenler” albümünü boşaltın.',
  vi='Dọn album “Đã xóa gần đây” trên iPhone để giải phóng {size}.',
  zh_Hans='清空 iPhone 上的“最近删除”相簿即可释放 {size}。',
  zh_Hant='清空 iPhone 上的「最近刪除」相簿即可釋放 {size}。')
s('v2Great', en='Great', ar='رائع', de='Super', es='Genial', fr='Super',
  he='מעולה', id='Mantap', it='Fantastico', ja='OK', ko='좋아요',
  pl='Super', pt='Ótimo', ro='Grozav', ru='Отлично', th='เยี่ยม',
  tr='Harika', vi='Tuyệt', zh_Hans='太好了', zh_Hant='太好了')

# ── Paywall ──
s('v2UnlockTitle', en='Unlock Unlimited Access', ar='افتح الوصول غير المحدود',
  de='Unbegrenzten Zugang freischalten', es='Desbloquea acceso ilimitado',
  fr='Débloquez l’accès illimité', he='פתחו גישה ללא הגבלה',
  id='Buka akses tanpa batas', it='Sblocca l’accesso illimitato',
  ja='すべての機能を無制限に', ko='무제한 이용 잠금 해제',
  pl='Odblokuj nieograniczony dostęp', pt='Desbloqueie acesso ilimitado',
  ro='Deblochează accesul nelimitat', ru='Откройте безлимитный доступ',
  th='ปลดล็อกการใช้งานไม่จำกัด', tr='Sınırsız erişimin kilidini açın',
  vi='Mở khóa truy cập không giới hạn', zh_Hans='解锁无限制使用',
  zh_Hant='解鎖無限制使用')
s('v2UnlockFeature1', en='Instantly find similar photos',
  ar='اعثر على الصور المتشابهة فورًا', de='Ähnliche Fotos sofort finden',
  es='Encuentra fotos parecidas al instante',
  fr='Trouvez instantanément les photos similaires',
  he='מציאת תמונות דומות מיד', id='Temukan foto mirip seketika',
  it='Trova subito le foto simili', ja='類似写真をすぐに発見',
  ko='유사한 사진을 바로 찾기', pl='Natychmiast znajduj podobne zdjęcia',
  pt='Encontre fotos parecidas num instante',
  ro='Găsește instant pozele similare', ru='Мгновенно находите похожие фото',
  th='ค้นหารูปที่คล้ายกันได้ทันที', tr='Benzer fotoğrafları anında bulun',
  vi='Tìm ảnh tương tự ngay lập tức', zh_Hans='立即找出相似照片',
  zh_Hant='立即找出相似照片')
s('v2UnlockFeature2', en='No limits on cleanup', ar='تنظيف بلا حدود',
  de='Aufräumen ohne Limits', es='Limpieza sin límites',
  fr='Nettoyage sans limite', he='ניקוי ללא הגבלה', id='Bersihkan tanpa batas',
  it='Pulizia senza limiti', ja='クリーンアップ無制限', ko='정리 횟수 무제한',
  pl='Sprzątanie bez limitów', pt='Limpeza sem limites',
  ro='Curățare fără limite', ru='Очистка без ограничений',
  th='ล้างได้ไม่จำกัด', tr='Sınırsız temizlik', vi='Dọn dẹp không giới hạn',
  zh_Hans='清理不设上限', zh_Hant='清理不設上限')
s('v2UnlockFeature3', en='Save both storage and time',
  ar='وفّر المساحة والوقت معًا', de='Spare Speicher und Zeit',
  es='Ahorra espacio y tiempo', fr='Gagnez de l’espace et du temps',
  he='חוסכים מקום וזמן', id='Hemat ruang dan waktu',
  it='Risparmia spazio e tempo', ja='容量も時間も節約', ko='공간과 시간 모두 절약',
  pl='Oszczędzaj miejsce i czas', pt='Poupe espaço e tempo',
  ro='Economisești spațiu și timp', ru='Экономьте место и время',
  th='ประหยัดทั้งพื้นที่และเวลา', tr='Hem yerden hem zamandan tasarruf',
  vi='Tiết kiệm cả dung lượng lẫn thời gian', zh_Hans='省空间也省时间',
  zh_Hant='省空間也省時間')
s('v2PrivacyLine', en='Your photos are analyzed on your device and never uploaded.',
  ar='تُحلَّل صورك على جهازك ولا تُرفع أبدًا.',
  de='Fotos werden auf dem Gerät analysiert und nie hochgeladen.',
  es='Tus fotos se analizan en tu dispositivo y nunca se suben.',
  fr='Vos photos sont analysées sur l’appareil et jamais envoyées.',
  he='התמונות מנותחות במכשיר ולעולם לא מועלות.',
  id='Foto dianalisis di perangkat Anda dan tidak pernah diunggah.',
  it='Le foto vengono analizzate sul dispositivo e mai caricate.',
  ja='写真はデバイス上で分析され、アップロードされません。',
  ko='사진은 기기에서 분석되며 업로드되지 않습니다.',
  pl='Zdjęcia są analizowane na urządzeniu i nigdy nie są wysyłane.',
  pt='As fotos são analisadas no dispositivo e nunca são enviadas.',
  ro='Pozele sunt analizate pe dispozitiv și nu sunt încărcate niciodată.',
  ru='Фото анализируются на устройстве и никуда не загружаются.',
  th='รูปของคุณได้รับการวิเคราะห์บนอุปกรณ์และไม่ถูกอัปโหลด',
  tr='Fotoğraflarınız cihazınızda analiz edilir, asla yüklenmez.',
  vi='Ảnh được phân tích ngay trên thiết bị và không bao giờ được tải lên.',
  zh_Hans='照片只在你的设备上分析，从不上传。',
  zh_Hant='照片只在你的裝置上分析，從不上傳。')
s('v2PerWeek', en='{price}/week, cancel anytime',
  ar='{price} أسبوعيًا، ألغِ في أي وقت',
  de='{price}/Woche, jederzeit kündbar', es='{price}/semana, cancela cuando quieras',
  fr='{price}/semaine, sans engagement', he='{price} לשבוע, ביטול בכל עת',
  id='{price}/minggu, batalkan kapan saja', it='{price}/settimana, disdici quando vuoi',
  ja='{price}/週・いつでも解約可', ko='주 {price}, 언제든 해지 가능',
  pl='{price}/tydzień, anuluj w każdej chwili', pt='{price}/semana, cancele quando quiser',
  ro='{price}/săptămână, anulezi oricând', ru='{price}/неделя, отмена в любой момент',
  th='{price}/สัปดาห์ ยกเลิกได้ทุกเมื่อ', tr='Haftalık {price}, istediğiniz zaman iptal',
  vi='{price}/tuần, hủy bất cứ lúc nào', zh_Hans='每周 {price}，可随时取消',
  zh_Hant='每週 {price}，可隨時取消')
s('v2PerYear', en='{price}/year', ar='{price} سنويًا', de='{price}/Jahr',
  es='{price}/año', fr='{price}/an', he='{price} לשנה', id='{price}/tahun',
  it='{price}/anno', ja='{price}/年', ko='연 {price}', pl='{price}/rok',
  pt='{price}/ano', ro='{price}/an', ru='{price}/год', th='{price}/ปี',
  tr='Yıllık {price}', vi='{price}/năm', zh_Hans='每年 {price}',
  zh_Hant='每年 {price}')
s('v2SavePercent', en='Save {percent}%', ar='وفّر {percent}%',
  de='{percent} % sparen', es='Ahorra un {percent} %', fr='Économisez {percent} %',
  he='חיסכון של {percent}%', id='Hemat {percent}%', it='Risparmi il {percent}%',
  ja='{percent}%お得', ko='{percent}% 절약', pl='Oszczędzasz {percent}%',
  pt='Poupe {percent}%', ro='Economisești {percent}%', ru='Скидка {percent}%',
  th='ประหยัด {percent}%', tr='%{percent} tasarruf', vi='Tiết kiệm {percent}%',
  zh_Hans='省 {percent}%', zh_Hant='省 {percent}%')
s('v2FreeTrialDays',
  en='{days, plural, one{1-day free trial} other{{days}-day free trial}}',
  ar='{days, plural, zero{تجربة مجانية} one{تجربة مجانية ليوم واحد} two{تجربة مجانية ليومين} few{تجربة مجانية لـ{days} أيام} many{تجربة مجانية لـ{days} يومًا} other{تجربة مجانية لـ{days} يوم}}',
  de='{days, plural, one{1 Tag gratis testen} other{{days} Tage gratis testen}}',
  es='{days, plural, one{Prueba gratis de 1 día} other{Prueba gratis de {days} días}}',
  fr='{days, plural, one{Essai gratuit de {days} jour} other{Essai gratuit de {days} jours}}',
  he='{days, plural, one{ניסיון חינם ליום אחד} two{ניסיון חינם ליומיים} other{ניסיון חינם ל־{days} ימים}}',
  id='{days, plural, other{Uji coba gratis {days} hari}}',
  it='{days, plural, one{Prova gratuita di 1 giorno} other{Prova gratuita di {days} giorni}}',
  ja='{days, plural, other{{days}日間の無料トライアル}}',
  ko='{days, plural, other{{days}일 무료 체험}}',
  pl='{days, plural, one{{days} dzień za darmo} few{{days} dni za darmo} many{{days} dni za darmo} other{{days} dnia za darmo}}',
  pt='{days, plural, one{Teste grátis de 1 dia} other{Teste grátis de {days} dias}}',
  ro='{days, plural, one{Probă gratuită de 1 zi} few{Probă gratuită de {days} zile} other{Probă gratuită de {days} de zile}}',
  ru='{days, plural, one{{days} день бесплатно} few{{days} дня бесплатно} many{{days} дней бесплатно} other{{days} дня бесплатно}}',
  th='{days, plural, other{ทดลองใช้ฟรี {days} วัน}}',
  tr='{days, plural, other{{days} gün ücretsiz deneme}}',
  vi='{days, plural, other{Dùng thử miễn phí {days} ngày}}',
  zh_Hans='{days, plural, other{{days} 天免费试用}}',
  zh_Hant='{days, plural, other{{days} 天免費試用}}')
s('v2StartFreeTrial',
  en='{days, plural, one{Start my 1-day free trial} other{Start my {days}-day free trial}}',
  ar='{days, plural, zero{ابدأ التجربة المجانية} one{ابدأ تجربتي المجانية ليوم واحد} two{ابدأ تجربتي المجانية ليومين} few{ابدأ تجربتي المجانية لـ{days} أيام} many{ابدأ تجربتي المجانية لـ{days} يومًا} other{ابدأ تجربتي المجانية لـ{days} يوم}}',
  de='{days, plural, one{1 Tag gratis testen} other{{days} Tage gratis testen}}',
  es='{days, plural, one{Empezar prueba gratis de 1 día} other{Empezar prueba gratis de {days} días}}',
  fr='{days, plural, one{Commencer l’essai gratuit de {days} jour} other{Commencer l’essai gratuit de {days} jours}}',
  he='{days, plural, one{התחלת ניסיון חינם ליום אחד} two{התחלת ניסיון חינם ליומיים} other{התחלת ניסיון חינם ל־{days} ימים}}',
  id='{days, plural, other{Mulai uji coba gratis {days} hari}}',
  it='{days, plural, one{Inizia la prova gratuita di 1 giorno} other{Inizia la prova gratuita di {days} giorni}}',
  ja='{days, plural, other{{days}日間の無料トライアルを開始}}',
  ko='{days, plural, other{{days}일 무료 체험 시작}}',
  pl='{days, plural, one{Zacznij {days} dzień za darmo} few{Zacznij {days} dni za darmo} many{Zacznij {days} dni za darmo} other{Zacznij {days} dnia za darmo}}',
  pt='{days, plural, one{Iniciar teste grátis de 1 dia} other{Iniciar teste grátis de {days} dias}}',
  ro='{days, plural, one{Începe proba gratuită de 1 zi} few{Începe proba gratuită de {days} zile} other{Începe proba gratuită de {days} de zile}}',
  ru='{days, plural, one{Начать: {days} день бесплатно} few{Начать: {days} дня бесплатно} many{Начать: {days} дней бесплатно} other{Начать: {days} дня бесплатно}}',
  th='{days, plural, other{เริ่มทดลองใช้ฟรี {days} วัน}}',
  tr='{days, plural, other{{days} günlük ücretsiz denemeyi başlat}}',
  vi='{days, plural, other{Bắt đầu dùng thử {days} ngày miễn phí}}',
  zh_Hans='{days, plural, other{开始 {days} 天免费试用}}',
  zh_Hant='{days, plural, other{開始 {days} 天免費試用}}')
s('v2FreeThen',
  en='{days, plural, one{Free for 1 day, then {price}} other{Free for {days} days, then {price}}}',
  ar='{days, plural, zero{مجانًا، ثم {price}} one{مجانًا ليوم واحد، ثم {price}} two{مجانًا ليومين، ثم {price}} few{مجانًا لـ{days} أيام، ثم {price}} many{مجانًا لـ{days} يومًا، ثم {price}} other{مجانًا لـ{days} يوم، ثم {price}}}',
  de='{days, plural, one{1 Tag gratis, danach {price}} other{{days} Tage gratis, danach {price}}}',
  es='{days, plural, one{Gratis 1 día, luego {price}} other{Gratis {days} días, luego {price}}}',
  fr='{days, plural, one{Gratuit {days} jour, puis {price}} other{Gratuit {days} jours, puis {price}}}',
  he='{days, plural, one{חינם ליום אחד, ואז {price}} two{חינם ליומיים, ואז {price}} other{חינם ל־{days} ימים, ואז {price}}}',
  id='{days, plural, other{Gratis {days} hari, lalu {price}}}',
  it='{days, plural, one{Gratis per 1 giorno, poi {price}} other{Gratis per {days} giorni, poi {price}}}',
  ja='{days, plural, other{{days}日間無料、その後{price}}}',
  ko='{days, plural, other{{days}일 무료, 이후 {price}}}',
  pl='{days, plural, one{{days} dzień za darmo, potem {price}} few{{days} dni za darmo, potem {price}} many{{days} dni za darmo, potem {price}} other{{days} dnia za darmo, potem {price}}}',
  pt='{days, plural, one{Grátis durante 1 dia, depois {price}} other{Grátis durante {days} dias, depois {price}}}',
  ro='{days, plural, one{Gratuit 1 zi, apoi {price}} few{Gratuit {days} zile, apoi {price}} other{Gratuit {days} de zile, apoi {price}}}',
  ru='{days, plural, one{{days} день бесплатно, затем {price}} few{{days} дня бесплатно, затем {price}} many{{days} дней бесплатно, затем {price}} other{{days} дня бесплатно, затем {price}}}',
  th='{days, plural, other{ฟรี {days} วัน จากนั้น {price}}}',
  tr='{days, plural, other{{days} gün ücretsiz, sonra {price}}}',
  vi='{days, plural, other{Miễn phí {days} ngày, sau đó {price}}}',
  zh_Hans='{days, plural, other{免费 {days} 天，之后 {price}}}',
  zh_Hant='{days, plural, other{免費 {days} 天，之後 {price}}}')
s('v2TrialEnabled', en='Free trial enabled', ar='تم تفعيل التجربة المجانية',
  de='Gratis-Testphase aktiv', es='Prueba gratis activada',
  fr='Essai gratuit activé', he='ניסיון חינם מופעל', id='Uji coba gratis aktif',
  it='Prova gratuita attiva', ja='無料トライアル有効', ko='무료 체험 사용 중',
  pl='Darmowy okres próbny włączony', pt='Teste grátis ativado',
  ro='Proba gratuită activată', ru='Бесплатный период включён',
  th='เปิดใช้การทดลองฟรีแล้ว', tr='Ücretsiz deneme etkin',
  vi='Đã bật dùng thử miễn phí', zh_Hans='已启用免费试用',
  zh_Hant='已啟用免費試用')
s('v2DueToday', en='Due today', ar='المستحق اليوم', de='Heute fällig',
  es='A pagar hoy', fr='À payer aujourd’hui', he='לתשלום היום',
  id='Bayar hari ini', it='Da pagare oggi', ja='本日のお支払い',
  ko='오늘 결제 금액', pl='Do zapłaty dziś', pt='A pagar hoje',
  ro='De plată azi', ru='К оплате сегодня', th='ชำระวันนี้',
  tr='Bugün ödenecek', vi='Thanh toán hôm nay', zh_Hans='今日应付',
  zh_Hant='今日應付')
s('v2DueOn', en='Due {date}', ar='المستحق في {date}', de='Fällig am {date}',
  es='A pagar el {date}', fr='À payer le {date}', he='לתשלום ב־{date}',
  id='Bayar pada {date}', it='Da pagare il {date}', ja='{date}のお支払い',
  ko='{date} 결제', pl='Do zapłaty {date}', pt='A pagar a {date}',
  ro='De plată pe {date}', ru='К оплате {date}', th='ชำระวันที่ {date}',
  tr='{date} tarihinde ödenecek', vi='Thanh toán ngày {date}',
  zh_Hans='{date} 应付', zh_Hant='{date} 應付')
s('v2DaysFree',
  en='{days, plural, one{1 day free} other{{days} days free}}',
  ar='{days, plural, zero{مجانًا} one{يوم مجاني} two{يومان مجانًا} few{{days} أيام مجانًا} many{{days} يومًا مجانًا} other{{days} يوم مجانًا}}',
  de='{days, plural, one{1 Tag gratis} other{{days} Tage gratis}}',
  es='{days, plural, one{1 día gratis} other{{days} días gratis}}',
  fr='{days, plural, one{{days} jour offert} other{{days} jours offerts}}',
  he='{days, plural, one{יום חינם} two{יומיים חינם} other{{days} ימים חינם}}',
  id='{days, plural, other{{days} hari gratis}}',
  it='{days, plural, one{1 giorno gratis} other{{days} giorni gratis}}',
  ja='{days, plural, other{{days}日間無料}}',
  ko='{days, plural, other{{days}일 무료}}',
  pl='{days, plural, one{{days} dzień gratis} few{{days} dni gratis} many{{days} dni gratis} other{{days} dnia gratis}}',
  pt='{days, plural, one{1 dia grátis} other{{days} dias grátis}}',
  ro='{days, plural, one{1 zi gratuită} few{{days} zile gratuite} other{{days} de zile gratuite}}',
  ru='{days, plural, one{{days} день бесплатно} few{{days} дня бесплатно} many{{days} дней бесплатно} other{{days} дня бесплатно}}',
  th='{days, plural, other{ฟรี {days} วัน}}',
  tr='{days, plural, other{{days} gün ücretsiz}}',
  vi='{days, plural, other{Miễn phí {days} ngày}}',
  zh_Hans='{days, plural, other{免费 {days} 天}}',
  zh_Hant='{days, plural, other{免費 {days} 天}}')
s('v2TryFree', en='Try Free', ar='جرّب مجانًا', de='Gratis testen',
  es='Probar gratis', fr='Essayer gratuitement', he='נסו בחינם',
  id='Coba gratis', it='Prova gratis', ja='無料で試す', ko='무료로 체험하기',
  pl='Wypróbuj za darmo', pt='Experimentar grátis', ro='Încearcă gratuit',
  ru='Попробовать бесплатно', th='ทดลองใช้ฟรี', tr='Ücretsiz dene',
  vi='Dùng thử miễn phí', zh_Hans='免费试用', zh_Hant='免費試用')
s('v2CleanYourStorage', en='Clean your Storage', ar='نظّف مساحة التخزين',
  de='Speicher aufräumen', es='Limpia tu almacenamiento',
  fr='Nettoyez votre stockage', he='נקו את האחסון',
  id='Bersihkan penyimpanan', it='Pulisci lo spazio',
  ja='ストレージをきれいに', ko='저장 공간 정리', pl='Wyczyść pamięć',
  pt='Limpe o armazenamento', ro='Curăță spațiul de stocare',
  ru='Очистите память', th='ล้างพื้นที่จัดเก็บ', tr='Depolamanızı temizleyin',
  vi='Dọn dẹp dung lượng', zh_Hans='清理存储空间', zh_Hant='清理儲存空間')
s('v2GetRidOf', en="Get rid of what you don't need",
  ar='تخلّص مما لا تحتاجه', de='Weg mit allem, was du nicht brauchst',
  es='Deshazte de lo que no necesitas', fr='Débarrassez-vous du superflu',
  he='היפטרו ממה שלא צריך', id='Singkirkan yang tidak Anda perlukan',
  it='Liberati di ciò che non ti serve', ja='いらないものを手放そう',
  ko='필요 없는 것은 비우세요', pl='Pozbądź się niepotrzebnych rzeczy',
  pt='Livre-se do que não precisa', ro='Scapă de ce nu îți trebuie',
  ru='Избавьтесь от лишнего', th='กำจัดสิ่งที่ไม่จำเป็น',
  tr='İhtiyacınız olmayandan kurtulun', vi='Loại bỏ những gì bạn không cần',
  zh_Hans='清掉不需要的东西', zh_Hant='清掉不需要的東西')
s('v2ProFeatures',
  en='Smart cleanup, video compression, secret space and no limits.',
  ar='تنظيف ذكي وضغط الفيديو ومساحة سرية وبلا حدود.',
  de='Smarte Bereinigung, Videokomprimierung, geheimer Bereich und keine Limits.',
  es='Limpieza inteligente, compresión de vídeo, espacio secreto y sin límites.',
  fr='Nettoyage intelligent, compression vidéo, espace secret et aucune limite.',
  he='ניקוי חכם, דחיסת סרטונים, מרחב סודי וללא הגבלות.',
  id='Pembersihan pintar, kompres video, ruang rahasia, dan tanpa batas.',
  it='Pulizia intelligente, compressione video, spazio segreto e nessun limite.',
  ja='スマート整理、ビデオ圧縮、シークレットスペース、制限なし。',
  ko='스마트 정리, 동영상 압축, 비밀 공간, 무제한 이용.',
  pl='Inteligentne czyszczenie, kompresja filmów, sejf i brak limitów.',
  pt='Limpeza inteligente, compressão de vídeo, espaço secreto e sem limites.',
  ro='Curățare inteligentă, comprimare video, spațiu secret și fără limite.',
  ru='Умная очистка, сжатие видео, тайное хранилище и никаких лимитов.',
  th='ล้างอัจฉริยะ บีบอัดวิดีโอ พื้นที่ลับ และไม่จำกัดการใช้งาน',
  tr='Akıllı temizlik, video sıkıştırma, gizli alan ve sınırsız kullanım.',
  vi='Dọn dẹp thông minh, nén video, không gian bí mật và không giới hạn.',
  zh_Hans='智能清理、视频压缩、私密空间，全部无限制。',
  zh_Hant='智慧清理、影片壓縮、私密空間，全部無限制。')

# ── Onboarding ──
s('v2WelcomeTitle', en='Welcome to {appName}', ar='مرحبًا بك في {appName}',
  de='Willkommen bei {appName}', es='Te damos la bienvenida a {appName}',
  fr='Bienvenue dans {appName}', he='ברוכים הבאים ל־{appName}',
  id='Selamat datang di {appName}', it='Benvenuto in {appName}',
  ja='{appName}へようこそ', ko='{appName}에 오신 것을 환영합니다',
  pl='Witaj w {appName}', pt='Bem-vindo à {appName}',
  ro='Bun venit în {appName}', ru='Добро пожаловать в {appName}',
  th='ยินดีต้อนรับสู่ {appName}', tr='{appName} uygulamasına hoş geldiniz',
  vi='Chào mừng đến với {appName}', zh_Hans='欢迎使用 {appName}',
  zh_Hant='歡迎使用 {appName}')
s('v2WelcomeAccess',
  en='{appName} needs access to your Photos to free up storage.',
  ar='يحتاج {appName} إلى الوصول إلى صورك لتحرير المساحة.',
  de='{appName} braucht Zugriff auf deine Fotos, um Speicher freizugeben.',
  es='{appName} necesita acceder a tus fotos para liberar espacio.',
  fr='{appName} a besoin d’accéder à vos Photos pour libérer de l’espace.',
  he='{appName} צריכה גישה לתמונות כדי לפנות מקום.',
  id='{appName} memerlukan akses ke Foto untuk mengosongkan ruang.',
  it='{appName} ha bisogno di accedere alle Foto per liberare spazio.',
  ja='{appName}は空き容量を増やすために写真へのアクセスが必要です。',
  ko='{appName}이(가) 공간을 확보하려면 사진 접근 권한이 필요합니다.',
  pl='{appName} potrzebuje dostępu do Zdjęć, aby zwolnić miejsce.',
  pt='{appName} precisa de acesso às Fotos para libertar espaço.',
  ro='{appName} are nevoie de acces la Poze pentru a elibera spațiu.',
  ru='{appName} нужен доступ к Фото, чтобы освободить место.',
  th='{appName} ต้องเข้าถึงรูปภาพเพื่อเพิ่มพื้นที่ว่าง',
  tr='{appName}, yer açmak için Fotoğraflar erişimine ihtiyaç duyar.',
  vi='{appName} cần quyền truy cập Ảnh để giải phóng dung lượng.',
  zh_Hans='{appName} 需要访问照片来释放空间。',
  zh_Hant='{appName} 需要存取照片來釋放空間。')
s('v2WelcomePrivacy',
  en='Your photos are analyzed on your device and never uploaded to our servers.',
  ar='تُحلَّل صورك على جهازك ولا تُرفع أبدًا إلى خوادمنا.',
  de='Deine Fotos werden auf dem Gerät analysiert und nie auf unsere Server geladen.',
  es='Tus fotos se analizan en tu dispositivo y nunca se suben a nuestros servidores.',
  fr='Vos photos sont analysées sur l’appareil et ne sont jamais envoyées sur nos serveurs.',
  he='התמונות מנותחות במכשיר ולעולם לא מועלות לשרתים שלנו.',
  id='Foto dianalisis di perangkat Anda dan tidak pernah diunggah ke server kami.',
  it='Le foto vengono analizzate sul dispositivo e mai caricate sui nostri server.',
  ja='写真はデバイス上で分析され、当社のサーバーにアップロードされることはありません。',
  ko='사진은 기기에서 분석되며 서버로 업로드되지 않습니다.',
  pl='Zdjęcia są analizowane na urządzeniu i nigdy nie trafiają na nasze serwery.',
  pt='As fotos são analisadas no dispositivo e nunca são enviadas para os nossos servidores.',
  ro='Pozele sunt analizate pe dispozitiv și nu ajung niciodată pe serverele noastre.',
  ru='Фото анализируются на устройстве и никогда не загружаются на наши серверы.',
  th='รูปของคุณได้รับการวิเคราะห์บนอุปกรณ์และไม่ถูกอัปโหลดไปยังเซิร์ฟเวอร์ของเรา',
  tr='Fotoğraflarınız cihazınızda analiz edilir, sunucularımıza asla yüklenmez.',
  vi='Ảnh được phân tích ngay trên thiết bị và không bao giờ được tải lên máy chủ của chúng tôi.',
  zh_Hans='照片只在你的设备上分析，绝不会上传到我们的服务器。',
  zh_Hant='照片只在你的裝置上分析，絕不會上傳到我們的伺服器。')
s('v2GetStarted', en='Get started', ar='ابدأ', de='Los geht’s',
  es='Empezar', fr='Commencer', he='מתחילים', id='Mulai',
  it='Inizia', ja='はじめる', ko='시작하기', pl='Zaczynamy',
  pt='Começar', ro='Începe', ru='Начать', th='เริ่มต้นใช้งาน',
  tr='Başla', vi='Bắt đầu', zh_Hans='开始使用', zh_Hant='開始使用')
s('v2Next', en='Next', ar='التالي', de='Weiter', es='Siguiente',
  fr='Suivant', he='הבא', id='Berikutnya', it='Avanti', ja='次へ',
  ko='다음', pl='Dalej', pt='Seguinte', ro='Înainte', ru='Далее',
  th='ถัดไป', tr='İleri', vi='Tiếp', zh_Hans='下一步', zh_Hant='下一步')
s('v2OnbDupTitle', en='Delete Duplicate Photos', ar='احذف الصور المكررة',
  de='Doppelte Fotos löschen', es='Elimina fotos duplicadas',
  fr='Supprimez les doublons', he='מחקו תמונות כפולות',
  id='Hapus foto duplikat', it='Elimina le foto doppie',
  ja='重複写真を削除', ko='중복 사진 삭제', pl='Usuń zduplikowane zdjęcia',
  pt='Apague fotos duplicadas', ro='Șterge pozele duplicate',
  ru='Удаляйте дубликаты фото', th='ลบรูปซ้ำ', tr='Kopya fotoğrafları silin',
  vi='Xóa ảnh trùng lặp', zh_Hans='删除重复照片', zh_Hant='刪除重複照片')
s('v2OnbDupBody', en='Find duplicate photos in seconds and reclaim your storage.',
  ar='اعثر على الصور المكررة في ثوانٍ واستعد مساحتك.',
  de='Finde Duplikate in Sekunden und hol dir Speicher zurück.',
  es='Encuentra duplicados en segundos y recupera tu espacio.',
  fr='Trouvez les doublons en quelques secondes et récupérez de l’espace.',
  he='מצאו כפילויות בשניות והחזירו לעצמכם מקום.',
  id='Temukan foto duplikat dalam hitungan detik dan dapatkan kembali ruang Anda.',
  it='Trova i duplicati in pochi secondi e recupera spazio.',
  ja='数秒で重複写真を見つけて、容量を取り戻しましょう。',
  ko='몇 초 만에 중복 사진을 찾아 저장 공간을 되찾으세요.',
  pl='Znajdź duplikaty w kilka sekund i odzyskaj miejsce.',
  pt='Encontre duplicados em segundos e recupere espaço.',
  ro='Găsește duplicatele în câteva secunde și recuperează spațiul.',
  ru='Находите дубликаты за секунды и возвращайте место.',
  th='ค้นหารูปซ้ำได้ในไม่กี่วินาทีและเรียกคืนพื้นที่ของคุณ',
  tr='Kopya fotoğrafları saniyeler içinde bulun, alanınızı geri kazanın.',
  vi='Tìm ảnh trùng trong vài giây và lấy lại dung lượng.',
  zh_Hans='几秒钟找出重复照片，收回存储空间。',
  zh_Hant='幾秒鐘找出重複照片，收回儲存空間。')
s('v2OnbSwipeTitle', en='Swipe to Clean', ar='اسحب للتنظيف',
  de='Wischen zum Aufräumen', es='Desliza para limpiar',
  fr='Balayez pour nettoyer', he='החליקו לניקוי', id='Geser untuk bersihkan',
  it='Scorri per pulire', ja='スワイプで整理', ko='밀어서 정리',
  pl='Przesuń, by posprzątać', pt='Deslize para limpar',
  ro='Glisează pentru curățare', ru='Смахивайте для очистки',
  th='ปัดเพื่อล้าง', tr='Kaydırarak temizleyin', vi='Vuốt để dọn',
  zh_Hans='滑动清理', zh_Hant='滑動清理')
s('v2OnbSwipeBody',
  en='Swipe left to delete, right to keep. Cleaning up has never been this quick.',
  ar='اسحب لليسار للحذف ولليمين للاحتفاظ. لم يكن التنظيف أسرع من ذلك.',
  de='Nach links zum Löschen, nach rechts zum Behalten. So schnell war Aufräumen noch nie.',
  es='Desliza a la izquierda para borrar y a la derecha para conservar. Nunca fue tan rápido.',
  fr='À gauche pour supprimer, à droite pour garder. Jamais le rangement n’a été si rapide.',
  he='שמאלה למחיקה, ימינה לשמירה. ניקוי מעולם לא היה מהיר כל כך.',
  id='Geser ke kiri untuk hapus, ke kanan untuk simpan. Bersih-bersih jadi secepat ini.',
  it='A sinistra per eliminare, a destra per tenere. Fare ordine non è mai stato così veloce.',
  ja='左で削除、右で保存。こんなに速く整理できるのは初めて。',
  ko='왼쪽으로 밀면 삭제, 오른쪽은 보관. 이렇게 빠른 정리는 처음일 거예요.',
  pl='W lewo usuń, w prawo zachowaj. Sprzątanie jeszcze nigdy nie było tak szybkie.',
  pt='Deslize para a esquerda para apagar e para a direita para manter. Nunca foi tão rápido.',
  ro='Glisează la stânga pentru ștergere, la dreapta pentru păstrare. Niciodată nu a fost atât de rapid.',
  ru='Влево — удалить, вправо — оставить. Так быстро ещё не было.',
  th='ปัดซ้ายเพื่อลบ ปัดขวาเพื่อเก็บ การจัดระเบียบไม่เคยเร็วขนาดนี้',
  tr='Silmek için sola, saklamak için sağa kaydırın. Temizlik hiç bu kadar hızlı olmamıştı.',
  vi='Vuốt trái để xóa, vuốt phải để giữ. Dọn dẹp chưa bao giờ nhanh đến thế.',
  zh_Hans='向左滑删除，向右滑保留。整理从未如此快速。',
  zh_Hant='向左滑刪除，向右滑保留。整理從未如此快速。')
s('v2OnbVideoTitle', en='Compress Videos', ar='اضغط الفيديوهات',
  de='Videos komprimieren', es='Comprime vídeos', fr='Compressez vos vidéos',
  he='דחסו סרטונים', id='Kompres video', it='Comprimi i video',
  ja='ビデオを圧縮', ko='동영상 압축', pl='Kompresuj filmy',
  pt='Comprima vídeos', ro='Comprimă clipurile', ru='Сжимайте видео',
  th='บีบอัดวิดีโอ', tr='Videoları sıkıştırın', vi='Nén video',
  zh_Hans='压缩视频', zh_Hant='壓縮影片')
s('v2OnbVideoBody', en='Shrink large videos and keep your memories.',
  ar='صغّر الفيديوهات الكبيرة واحتفظ بذكرياتك.',
  de='Verkleinere große Videos und behalte deine Erinnerungen.',
  es='Reduce los vídeos grandes y conserva tus recuerdos.',
  fr='Allégez les grosses vidéos et gardez vos souvenirs.',
  he='הקטינו סרטונים גדולים ושמרו על הזיכרונות.',
  id='Perkecil video besar dan tetap simpan kenangan Anda.',
  it='Riduci i video pesanti e conserva i tuoi ricordi.',
  ja='大きなビデオを小さくして、思い出はそのまま残しましょう。',
  ko='큰 동영상은 작게 줄이고 추억은 그대로 남기세요.',
  pl='Zmniejsz duże filmy i zachowaj wspomnienia.',
  pt='Reduza os vídeos grandes e guarde as suas memórias.',
  ro='Micșorează clipurile mari și păstrează-ți amintirile.',
  ru='Уменьшайте большие видео и сохраняйте воспоминания.',
  th='ลดขนาดวิดีโอใหญ่และเก็บความทรงจำไว้',
  tr='Büyük videoları küçültün, anılarınızı koruyun.',
  vi='Thu nhỏ video lớn mà vẫn giữ lại kỷ niệm.',
  zh_Hans='缩小大视频，留住回忆。', zh_Hant='縮小大影片，留住回憶。')
s('v2TryDays',
  en='{days, plural, one{Try 1 day} other{Try {days} days}}',
  ar='{days, plural, zero{جرّب} one{جرّب يومًا واحدًا} two{جرّب يومين} few{جرّب {days} أيام} many{جرّب {days} يومًا} other{جرّب {days} يوم}}',
  de='{days, plural, one{1 Tag testen} other{{days} Tage testen}}',
  es='{days, plural, one{Prueba 1 día} other{Prueba {days} días}}',
  fr='{days, plural, one{Essayez {days} jour} other{Essayez {days} jours}}',
  he='{days, plural, one{נסו יום אחד} two{נסו יומיים} other{נסו {days} ימים}}',
  id='{days, plural, other{Coba {days} hari}}',
  it='{days, plural, one{Prova 1 giorno} other{Prova {days} giorni}}',
  ja='{days, plural, other{{days}日間お試し}}',
  ko='{days, plural, other{{days}일 체험}}',
  pl='{days, plural, one{Wypróbuj {days} dzień} few{Wypróbuj {days} dni} many{Wypróbuj {days} dni} other{Wypróbuj {days} dnia}}',
  pt='{days, plural, one{Experimente 1 dia} other{Experimente {days} dias}}',
  ro='{days, plural, one{Încearcă 1 zi} few{Încearcă {days} zile} other{Încearcă {days} de zile}}',
  ru='{days, plural, one{Попробуйте {days} день} few{Попробуйте {days} дня} many{Попробуйте {days} дней} other{Попробуйте {days} дня}}',
  th='{days, plural, other{ทดลองใช้ {days} วัน}}',
  tr='{days, plural, other{{days} gün deneyin}}',
  vi='{days, plural, other{Dùng thử {days} ngày}}',
  zh_Hans='{days, plural, other{试用 {days} 天}}',
  zh_Hant='{days, plural, other{試用 {days} 天}}')
s('v2ForFree', en='For free!', ar='مجانًا!', de='Kostenlos!', es='¡Gratis!',
  fr='Gratuitement !', he='בחינם!', id='Gratis!', it='Gratis!',
  ja='無料！', ko='무료로!', pl='Za darmo!', pt='Grátis!', ro='Gratuit!',
  ru='Бесплатно!', th='ฟรี!', tr='Ücretsiz!', vi='Miễn phí!',
  zh_Hans='免费！', zh_Hant='免費！')

# ── Extras ──
s('v2ExtrasTitle', en='Extra Tools', ar='أدوات إضافية', de='Weitere Tools',
  es='Herramientas extra', fr='Outils en plus', he='כלים נוספים',
  id='Alat tambahan', it='Strumenti extra', ja='便利ツール', ko='추가 도구',
  pl='Dodatkowe narzędzia', pt='Ferramentas extra', ro='Instrumente extra',
  ru='Доп. инструменты', th='เครื่องมือเพิ่มเติม', tr='Ek araçlar',
  vi='Công cụ bổ sung', zh_Hans='更多工具', zh_Hant='更多工具')
s('v2ExtrasUtilities', en='Utilities', ar='أدوات مساعدة', de='Werkzeuge',
  es='Utilidades', fr='Utilitaires', he='כלים', id='Utilitas',
  it='Utility', ja='ユーティリティ', ko='유틸리티', pl='Narzędzia',
  pt='Utilitários', ro='Utilitare', ru='Утилиты', th='ยูทิลิตี้',
  tr='Araçlar', vi='Tiện ích', zh_Hans='实用工具', zh_Hant='實用工具')
s('v2ExtrasPrivate', en='Private', ar='خاص', de='Privat', es='Privado',
  fr='Privé', he='פרטי', id='Pribadi', it='Privato', ja='プライベート',
  ko='개인', pl='Prywatne', pt='Privado', ro='Privat', ru='Личное',
  th='ส่วนตัว', tr='Gizli', vi='Riêng tư', zh_Hans='隐私', zh_Hant='隱私')
s('v2ChargingTitle', en='Charging Animation', ar='رسوم الشحن المتحركة',
  de='Lade-Animation', es='Animación de carga', fr='Animation de charge',
  he='אנימציית טעינה', id='Animasi pengisian daya', it='Animazione di ricarica',
  ja='充電アニメーション', ko='충전 애니메이션', pl='Animacja ładowania',
  pt='Animação de carregamento', ro='Animație de încărcare',
  ru='Анимация зарядки', th='แอนิเมชันการชาร์จ', tr='Şarj animasyonu',
  vi='Hiệu ứng sạc pin', zh_Hans='充电动画', zh_Hant='充電動畫')
s('v2ChargingBody', en='Personalize your charging screen',
  ar='خصّص شاشة الشحن', de='Gestalte deinen Ladebildschirm',
  es='Personaliza la pantalla de carga', fr='Personnalisez l’écran de charge',
  he='התאימו אישית את מסך הטעינה', id='Personalisasi layar pengisian daya',
  it='Personalizza la schermata di ricarica', ja='充電画面をカスタマイズ',
  ko='충전 화면을 꾸며 보세요', pl='Spersonalizuj ekran ładowania',
  pt='Personalize o ecrã de carregamento', ro='Personalizează ecranul de încărcare',
  ru='Настройте экран зарядки', th='ปรับแต่งหน้าจอขณะชาร์จ',
  tr='Şarj ekranınızı kişiselleştirin', vi='Tùy chỉnh màn hình sạc',
  zh_Hans='个性化你的充电画面', zh_Hant='個人化你的充電畫面')
s('v2SecretTitle', en='Secret Library', ar='المكتبة السرية',
  de='Geheime Mediathek', es='Biblioteca secreta', fr='Photothèque secrète',
  he='ספרייה סודית', id='Pustaka rahasia', it='Libreria segreta',
  ja='シークレットライブラリ', ko='비밀 보관함', pl='Tajna biblioteka',
  pt='Biblioteca secreta', ro='Bibliotecă secretă', ru='Тайная медиатека',
  th='คลังลับ', tr='Gizli arşiv', vi='Thư viện bí mật',
  zh_Hans='私密相册', zh_Hant='私密相簿')
s('v2SecretBody', en='Protect your private photos', ar='احمِ صورك الخاصة',
  de='Schütze deine privaten Fotos', es='Protege tus fotos privadas',
  fr='Protégez vos photos privées', he='הגנו על התמונות הפרטיות',
  id='Lindungi foto pribadi Anda', it='Proteggi le tue foto private',
  ja='プライベートな写真を保護', ko='개인 사진을 보호하세요',
  pl='Chroń prywatne zdjęcia', pt='Proteja as suas fotos privadas',
  ro='Protejează-ți pozele private', ru='Защитите личные фото',
  th='ปกป้องรูปส่วนตัวของคุณ', tr='Özel fotoğraflarınızı koruyun',
  vi='Bảo vệ ảnh riêng tư', zh_Hans='保护你的私密照片',
  zh_Hant='保護你的私密照片')


# ── Daily free limit (2026-09-29, mirrors Cleanup: 5 items per day) ──
PLACEHOLDERS.update({
    'v2DailyLimitBody': {'limit': 'int'},
    'v2DailyLimitRemaining': {'count': 'int'},
})
s('v2DailyLimitTitle', en="You've reached your daily removal limit",
  ar='لقد وصلت إلى حد الحذف اليومي', de='Tageslimit zum Löschen erreicht',
  es='Has alcanzado el límite diario de eliminación',
  fr='Limite quotidienne de suppression atteinte',
  he='הגעתם למגבלת המחיקה היומית', id='Batas penghapusan harian tercapai',
  it='Hai raggiunto il limite giornaliero di eliminazione',
  ja='本日の削除上限に達しました', ko='오늘의 삭제 한도에 도달했습니다',
  pl='Osiągnięto dzienny limit usuwania', pt='Atingiu o limite diário de eliminação',
  ro='Ai atins limita zilnică de ștergere', ru='Достигнут дневной лимит удаления',
  th='ถึงขีดจำกัดการลบรายวันแล้ว', tr='Günlük silme sınırına ulaştınız',
  vi='Bạn đã đạt giới hạn xóa trong ngày', zh_Hans='已达到今日删除上限',
  zh_Hant='已達到今日刪除上限')
s('v2DailyLimitBody',
  en='You can delete {limit} items a day with the free version. Unlock Pro to remove the limit.',
  ar='يمكنك حذف {limit} عناصر يوميًا في النسخة المجانية. افتح Pro لإزالة الحد.',
  de='In der Gratisversion kannst du {limit} Objekte pro Tag löschen. Schalte Pro frei, um das Limit aufzuheben.',
  es='Con la versión gratuita puedes eliminar {limit} elementos al día. Desbloquea Pro para quitar el límite.',
  fr='La version gratuite permet de supprimer {limit} éléments par jour. Débloquez Pro pour lever la limite.',
  he='בגרסה החינמית אפשר למחוק {limit} פריטים ביום. פתחו את Pro כדי להסיר את המגבלה.',
  id='Versi gratis dapat menghapus {limit} item per hari. Buka Pro untuk menghapus batas.',
  it='Con la versione gratuita puoi eliminare {limit} elementi al giorno. Sblocca Pro per rimuovere il limite.',
  ja='無料版では1日に{limit}件まで削除できます。Proで制限を解除できます。',
  ko='무료 버전은 하루에 {limit}개까지 삭제할 수 있습니다. Pro로 한도를 해제하세요.',
  pl='W wersji darmowej możesz usunąć {limit} elementów dziennie. Odblokuj Pro, aby znieść limit.',
  pt='Na versão gratuita pode apagar {limit} itens por dia. Desbloqueie o Pro para remover o limite.',
  ro='Versiunea gratuită permite ștergerea a {limit} elemente pe zi. Deblochează Pro pentru a elimina limita.',
  ru='В бесплатной версии можно удалять {limit} объектов в день. Откройте Pro, чтобы снять лимит.',
  th='เวอร์ชันฟรีลบได้วันละ {limit} รายการ ปลดล็อก Pro เพื่อยกเลิกขีดจำกัด',
  tr='Ücretsiz sürümde günde {limit} öge silebilirsiniz. Sınırı kaldırmak için Pro’ya geçin.',
  vi='Bản miễn phí chỉ xóa được {limit} mục mỗi ngày. Mở khóa Pro để bỏ giới hạn.',
  zh_Hans='免费版每天可删除 {limit} 项。解锁 Pro 即可取消限制。',
  zh_Hant='免費版每天可刪除 {limit} 項。解鎖 Pro 即可取消限制。')
s('v2DailyLimitRemaining',
  en='{count, plural, one{You can delete 1 more item today for free. Select fewer items or unlock Pro.} other{You can delete {count} more items today for free. Select fewer items or unlock Pro.}}',
  ar='{count, plural, zero{لا يمكنك حذف المزيد اليوم مجانًا. حدّد عناصر أقل أو افتح Pro.} one{يمكنك حذف عنصر واحد آخر اليوم مجانًا. حدّد عناصر أقل أو افتح Pro.} two{يمكنك حذف عنصرين آخرين اليوم مجانًا. حدّد عناصر أقل أو افتح Pro.} few{يمكنك حذف {count} عناصر أخرى اليوم مجانًا. حدّد عناصر أقل أو افتح Pro.} many{يمكنك حذف {count} عنصرًا آخر اليوم مجانًا. حدّد عناصر أقل أو افتح Pro.} other{يمكنك حذف {count} عنصر آخر اليوم مجانًا. حدّد عناصر أقل أو افتح Pro.}}',
  de='{count, plural, one{Heute kannst du noch 1 Objekt gratis löschen. Wähle weniger aus oder schalte Pro frei.} other{Heute kannst du noch {count} Objekte gratis löschen. Wähle weniger aus oder schalte Pro frei.}}',
  es='{count, plural, one{Hoy puedes eliminar 1 elemento más gratis. Selecciona menos o desbloquea Pro.} other{Hoy puedes eliminar {count} elementos más gratis. Selecciona menos o desbloquea Pro.}}',
  fr='{count, plural, one{Vous pouvez encore supprimer {count} élément gratuitement aujourd’hui. Sélectionnez-en moins ou débloquez Pro.} other{Vous pouvez encore supprimer {count} éléments gratuitement aujourd’hui. Sélectionnez-en moins ou débloquez Pro.}}',
  he='{count, plural, one{היום אפשר למחוק בחינם עוד פריט אחד. בחרו פחות פריטים או פתחו את Pro.} two{היום אפשר למחוק בחינם עוד שני פריטים. בחרו פחות פריטים או פתחו את Pro.} other{היום אפשר למחוק בחינם עוד {count} פריטים. בחרו פחות פריטים או פתחו את Pro.}}',
  id='{count, plural, other{Hari ini Anda masih bisa menghapus {count} item gratis. Pilih lebih sedikit atau buka Pro.}}',
  it='{count, plural, one{Oggi puoi eliminare ancora 1 elemento gratis. Selezionane meno o sblocca Pro.} other{Oggi puoi eliminare ancora {count} elementi gratis. Selezionane meno o sblocca Pro.}}',
  ja='{count, plural, other{本日あと{count}件まで無料で削除できます。選択を減らすか、Proを解除してください。}}',
  ko='{count, plural, other{오늘은 {count}개 더 무료로 삭제할 수 있습니다. 선택을 줄이거나 Pro를 이용하세요.}}',
  pl='{count, plural, one{Dziś możesz jeszcze usunąć za darmo {count} element. Zaznacz mniej lub odblokuj Pro.} few{Dziś możesz jeszcze usunąć za darmo {count} elementy. Zaznacz mniej lub odblokuj Pro.} many{Dziś możesz jeszcze usunąć za darmo {count} elementów. Zaznacz mniej lub odblokuj Pro.} other{Dziś możesz jeszcze usunąć za darmo {count} elementu. Zaznacz mniej lub odblokuj Pro.}}',
  pt='{count, plural, one{Hoje ainda pode apagar 1 item grátis. Selecione menos ou desbloqueie o Pro.} other{Hoje ainda pode apagar {count} itens grátis. Selecione menos ou desbloqueie o Pro.}}',
  ro='{count, plural, one{Azi mai poți șterge gratuit 1 element. Selectează mai puține sau deblochează Pro.} few{Azi mai poți șterge gratuit {count} elemente. Selectează mai puține sau deblochează Pro.} other{Azi mai poți șterge gratuit {count} de elemente. Selectează mai puține sau deblochează Pro.}}',
  ru='{count, plural, one{Сегодня можно бесплатно удалить ещё {count} объект. Выберите меньше или откройте Pro.} few{Сегодня можно бесплатно удалить ещё {count} объекта. Выберите меньше или откройте Pro.} many{Сегодня можно бесплатно удалить ещё {count} объектов. Выберите меньше или откройте Pro.} other{Сегодня можно бесплатно удалить ещё {count} объекта. Выберите меньше или откройте Pro.}}',
  th='{count, plural, other{วันนี้ลบฟรีได้อีก {count} รายการ เลือกให้น้อยลงหรือปลดล็อก Pro}}',
  tr='{count, plural, other{Bugün {count} öge daha ücretsiz silebilirsiniz. Daha az seçin veya Pro’ya geçin.}}',
  vi='{count, plural, other{Hôm nay bạn còn xóa miễn phí được {count} mục. Hãy chọn ít hơn hoặc mở khóa Pro.}}',
  zh_Hans='{count, plural, other{今天还能免费删除 {count} 项。请减少选择，或解锁 Pro。}}',
  zh_Hant='{count, plural, other{今天還能免費刪除 {count} 項。請減少選取，或解鎖 Pro。}}')
s('v2SeeProOptions', en='See Pro Options', ar='عرض خيارات Pro',
  de='Pro-Optionen ansehen', es='Ver opciones Pro', fr='Voir les offres Pro',
  he='הצגת אפשרויות Pro', id='Lihat opsi Pro', it='Vedi le opzioni Pro',
  ja='Proプランを見る', ko='Pro 옵션 보기', pl='Zobacz opcje Pro',
  pt='Ver opções Pro', ro='Vezi opțiunile Pro', ru='Посмотреть Pro',
  th='ดูตัวเลือก Pro', tr='Pro seçeneklerini gör', vi='Xem các gói Pro',
  zh_Hans='查看 Pro 方案', zh_Hant='查看 Pro 方案')


RTL = {'ar', 'he'}
FSI, PDI = '⁨', '⁩'


def isolate(language, key, message):
    if language not in RTL:
        return message
    for name, kind in PLACEHOLDERS.get(key, {}).items():
        if kind == 'String':
            message = message.replace('{' + name + '}', FSI + '{' + name + '}' + PDI)
    return message


def main():
    missing = [(k, lang) for k, v in S.items() for lang in LANGS if lang not in v]
    if missing:
        raise SystemExit(f'Missing translations: {missing[:10]}')
    files = {lang: L10N / f'app_{lang}.arb' for lang in LANGS}
    files['zh'] = L10N / 'app_zh.arb'
    for lang, path in files.items():
        source_lang = 'zh_Hans' if lang == 'zh' else lang
        data = json.loads(path.read_text(encoding='utf-8-sig'),
                          object_pairs_hook=OrderedDict)
        for key, messages in S.items():
            data[key] = isolate(source_lang, key, messages[source_lang])
            if lang == 'en' and key in PLACEHOLDERS:
                data['@' + key] = {
                    'placeholders': {
                        name: {'type': kind}
                        for name, kind in PLACEHOLDERS[key].items()
                    }
                }
        path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + '\n',
                        encoding='utf-8')
    print(f'Merged {len(S)} keys into {len(files)} catalogs')


if __name__ == '__main__':
    main()
